import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'de';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation & Tabs
    'nav.weekPlanner': 'Week Planner',
    'nav.recipes': 'Recipes',
    'nav.dashboard': 'Dashboard',
    'nav.tasks': 'Tasks',
    'nav.calendar': 'Calendar',
    'nav.notes': 'Notes',
    'nav.habits': 'Habits',
    'nav.contacts': 'Contacts',
    'nav.contracts': 'Contracts',
    'nav.family': 'Family',
    'nav.settings': 'Settings',
    'nav.assistant': 'Assistant',
    'nav.chat': 'Chat',
    'nav.calls': 'Calls',
    'nav.projects': 'Projects',
    'nav.activity': 'Activity',
    'nav.admin': 'Admin',
    'nav.search': 'Search',
    'nav.todayFocus': "Today's Focus",
    'nav.focusMode': 'Focus Mode',
    'nav.weeklyReview': 'Weekly Review',
    'nav.voiceMode': 'Voice Mode',
    'nav.signOut': 'Sign Out',
    'nav.main': 'Main',
    'nav.productivity': 'Productivity',
    
    // Meal Planning
    'meals.generateShoppingList': 'Generate Shopping List',
    'meals.addRecipe': 'Add Recipe',
    'meals.addMeal': 'Add',
    'meals.noMeals': 'No meals',
    'meals.servings': 'servings',
    'meals.mealPlanned': 'meal planned',
    'meals.mealsPlanned': 'meals planned',
    'meals.removeMeal': 'Remove meal',
    'meals.dragToMove': 'Drag to move',
    'meals.mealDetails': 'Meal Details',
    'meals.recipe': 'Recipe',
    'meals.notes': 'Notes',
    'meals.noNotes': 'No notes',
    'meals.viewRecipe': 'View Recipe',
    'meals.prepTime': 'Prep time',
    'meals.cookTime': 'Cook time',
    'meals.minutes': 'min',
    'meals.dropHere': 'Drop here',
    
    // Meal Types
    'mealType.breakfast': 'Breakfast',
    'mealType.lunch': 'Lunch',
    'mealType.dinner': 'Dinner',
    'mealType.snack': 'Snack',
    
    // Days
    'day.mon': 'Mon',
    'day.tue': 'Tue',
    'day.wed': 'Wed',
    'day.thu': 'Thu',
    'day.fri': 'Fri',
    'day.sat': 'Sat',
    'day.sun': 'Sun',
    
    // Common
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.add': 'Add',
    'common.loading': 'Loading...',
    'common.language': 'Language',
    'common.english': 'English',
    'common.german': 'German',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.all': 'All',
    'common.today': 'Today',
    'common.tomorrow': 'Tomorrow',
    'common.yesterday': 'Yesterday',
    'common.thisWeek': 'This Week',
    'common.completed': 'Completed',
    'common.pending': 'Pending',
    'common.overdue': 'Overdue',
    'common.priority': 'Priority',
    'common.dueDate': 'Due Date',
    'common.category': 'Category',
    'common.description': 'Description',
    'common.title': 'Title',
    'common.name': 'Name',
    'common.email': 'Email',
    'common.phone': 'Phone',
    'common.address': 'Address',
    'common.notes': 'Notes',
    'common.status': 'Status',
    'common.actions': 'Actions',
    'common.view': 'View',
    'common.close': 'Close',
    'common.confirm': 'Confirm',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.new': 'New',
    'common.create': 'Create',
    'common.update': 'Update',
    'common.remove': 'Remove',
    
    // Recipe Dialog
    'recipe.name': 'Recipe Name',
    'recipe.description': 'Description',
    'recipe.category': 'Category',
    'recipe.servings': 'Servings',
    'recipe.prepTime': 'Prep Time (minutes)',
    'recipe.cookTime': 'Cook Time (minutes)',
    'recipe.instructions': 'Instructions',
    'recipe.ingredients': 'Ingredients',
    'recipe.addRecipe': 'Add Recipe',
    'recipe.editRecipe': 'Edit Recipe',
    'recipe.noDetails': 'No recipe details available.',
    'recipe.notFound': 'Recipe not found.',
    'recipe.other': 'Other',
    'recipe.cookingMode': 'Cooking Mode',
    'recipe.step': 'Step',
    'recipe.of': 'of',
    'recipe.previous': 'Previous',
    'recipe.next': 'Next',
    'recipe.done': 'Done',
    'recipe.startCooking': 'Start Cooking',
    
    // Add Meal Dialog
    'addMeal.title': 'Add Meal',
    'addMeal.date': 'Date',
    'addMeal.mealType': 'Meal Type',
    'addMeal.selectRecipe': 'Select a recipe',
    'addMeal.orCustomMeal': 'Or enter custom meal name',
    'addMeal.customMealName': 'Custom Meal Name',
    'addMeal.servings': 'Servings',
    'addMeal.notes': 'Notes (optional)',
    
    // Dashboard
    'dashboard.title': 'Productivity Dashboard',
    'dashboard.subtitle': 'Track your progress and insights',
    'dashboard.thisWeek': 'This Week',
    'dashboard.thisMonth': 'This Month',
    'dashboard.streak': 'Streak',
    'dashboard.peakHours': 'Peak Hours',
    'dashboard.tasksCompleted': 'tasks completed',
    'dashboard.consecutiveDays': 'consecutive days',
    'dashboard.mostProductive': 'most productive',
    'dashboard.categoryBreakdown': 'Category Breakdown',
    'dashboard.productivityByHour': 'Productivity by Hour',
    'dashboard.upcomingDeadlines': 'Upcoming Deadlines (Next 7 Days)',
    'dashboard.noDeadlines': 'No upcoming deadlines',
    'dashboard.noTasks': 'No tasks',
    'dashboard.completionRate': 'Completion Rate',
    'dashboard.business': 'Business',
    'dashboard.personal': 'Personal',
    'dashboard.family': 'Family',
    'dashboard.more': 'more',
    'dashboard.welcome': 'Welcome',
    'dashboard.overview': 'Overview',
    'dashboard.tasksToday': 'Tasks Today',
    'dashboard.upcomingEvents': 'Upcoming Events',
    'dashboard.recentActivity': 'Recent Activity',
    'dashboard.quickActions': 'Quick Actions',
    'dashboard.statistics': 'Statistics',
    'dashboard.progress': 'Progress',
    
    // Tasks
    'tasks.title': 'Tasks',
    'tasks.addTask': 'Add Task',
    'tasks.newTask': 'New Task',
    'tasks.editTask': 'Edit Task',
    'tasks.deleteTask': 'Delete Task',
    'tasks.markComplete': 'Mark Complete',
    'tasks.markIncomplete': 'Mark Incomplete',
    'tasks.noTasks': 'No tasks',
    'tasks.allCompleted': 'All tasks completed!',
    'tasks.dueToday': 'Due Today',
    'tasks.overdue': 'Overdue',
    'tasks.upcoming': 'Upcoming',
    'tasks.completed': 'Completed',
    'tasks.highPriority': 'High Priority',
    'tasks.mediumPriority': 'Medium Priority',
    'tasks.lowPriority': 'Low Priority',
    
    // Calendar
    'calendar.title': 'Calendar',
    'calendar.today': 'Today',
    'calendar.month': 'Month',
    'calendar.week': 'Week',
    'calendar.day': 'Day',
    'calendar.addEvent': 'Add Event',
    'calendar.editEvent': 'Edit Event',
    'calendar.deleteEvent': 'Delete Event',
    'calendar.noEvents': 'No events',
    'calendar.allDay': 'All Day',
    
    // Settings
    'settings.title': 'Settings',
    'settings.profile': 'Profile',
    'settings.account': 'Account',
    'settings.preferences': 'Preferences',
    'settings.notifications': 'Notifications',
    'settings.appearance': 'Appearance',
    'settings.language': 'Language',
    'settings.theme': 'Theme',
    'settings.dark': 'Dark',
    'settings.light': 'Light',
    'settings.darkMode': 'Dark Mode',
    'settings.lightMode': 'Light Mode',
    'settings.systemMode': 'System',
    'settings.save': 'Save Settings',
    'settings.saved': 'Settings saved',
    'settings.accentColor': 'Accent Color',
    'settings.taskReminders': 'Task Reminders',
    'settings.taskRemindersDesc': 'Get notified before task deadlines',
    'settings.calendarAlerts': 'Calendar Alerts',
    'settings.calendarAlertsDesc': 'Reminders before scheduled events',
    'settings.reminderTime': 'Reminder Time',
    'settings.minutesBefore': 'minutes before',
    'settings.defaultCategory': 'Default Task Category',
    'settings.defaultPriority': 'Default Task Priority',
    'settings.defaults': 'Defaults',
    'settings.team': 'Team',
    
    // Contacts
    'contacts.title': 'Contacts',
    'contacts.addContact': 'Add Contact',
    'contacts.editContact': 'Edit Contact',
    'contacts.deleteContact': 'Delete Contact',
    'contacts.noContacts': 'No contacts',
    'contacts.searchContacts': 'Search contacts...',
    
    // Habits
    'habits.title': 'Habits',
    'habits.addHabit': 'Add Habit',
    'habits.editHabit': 'Edit Habit',
    'habits.deleteHabit': 'Delete Habit',
    'habits.streak': 'Streak',
    'habits.completed': 'Completed',
    'habits.noHabits': 'No habits',
    'habits.daily': 'Daily',
    'habits.weekly': 'Weekly',
    
    // Projects
    'projects.title': 'Projects',
    'projects.addProject': 'Add Project',
    'projects.editProject': 'Edit Project',
    'projects.deleteProject': 'Delete Project',
    'projects.noProjects': 'No projects',
    'projects.archived': 'Archived',
    'projects.active': 'Active',
    
    // Task Categories & Priorities
    'category.personal': 'Personal',
    'category.business': 'Business',
    'category.family': 'Family',
    'category.all': 'All',
    'category.shared': 'Shared',
    'priority.low': 'Low',
    'priority.medium': 'Medium',
    'priority.high': 'High',
    
    // Task List
    'taskList.addTask': 'Add Task',
    'taskList.newTask': 'New task...',
    'taskList.overdue': 'Overdue',
    'taskList.setDueDate': 'Set due date',
    'taskList.clearDueDate': 'Clear due date',
    'taskList.deleteSelected': 'Delete selected',
    'taskList.cancel': 'Cancel',
    'taskList.noTasks': 'No tasks yet',
    'taskList.startAdding': 'Start adding tasks to get productive!',
    'taskList.completed': 'Completed',
    'taskList.editTask': 'Edit task',
    'taskList.addSubtask': 'Add subtask',
    'taskList.sharedBy': 'Shared by',
    'taskList.event': 'Event',
    'taskList.task': 'Task',
    
    // Time Filters
    'time.all': 'All',
    'time.today': 'Today',
    'time.week': 'Week',
    'time.month': 'Month',
    'time.noDate': 'No Date',
    
    // Calendar Panel
    'calendar.agenda': 'Agenda',
    'calendar.import': 'Import',
    'calendar.invalidFile': 'Invalid File',
    'calendar.invalidFileDesc': 'Please upload a valid .ics calendar file.',
    'calendar.noEventsFound': 'No Events Found',
    'calendar.noEventsFoundDesc': 'The file does not contain any valid events.',
    'calendar.importSuccess': 'Import Successful',
    'calendar.importedEvents': 'Imported {count} event(s).',
    'calendar.importFailed': 'Import Failed',
    'calendar.importFailedDesc': 'Failed to parse the calendar file. Please check the format.',
    'calendar.updatedSuccess': 'Updated successfully',
    'calendar.deletedSuccess': 'Deleted successfully',
    'calendar.noUpcoming': 'No upcoming events or tasks',
    'calendar.tasksWithDueDates': 'Tasks with due dates will appear here',
    'calendar.importIcs': 'Import .ics',
    'calendar.scheduleSomething': 'Schedule something',
    'calendar.sharedBy': 'Shared by',
    
    // Notes Panel
    'notes.title': 'Notes',
    'notes.newNote': 'New Note',
    'notes.searchNotes': 'Search notes...',
    'notes.noNotes': 'No notes yet',
    'notes.createFirst': 'Create your first note',
    'notes.noContent': 'No content',
    
    // Habits Panel
    'habits.habitsAndGoals': 'Habits & Goals',
    'habits.todaysProgress': "Today's Progress",
    'habits.addNewHabit': 'Add New Habit',
    'habits.noHabitsYet': 'No habits yet',
    'habits.createFirstHabit': 'Create your first habit to start tracking',
    'habits.goals': 'Goals',
    'habits.addNewGoal': 'Add New Goal',
    'habits.noGoalsYet': 'No goals yet',
    'habits.setGoal': 'Set a goal to track your progress',
    'habits.target': 'Target',
    'habits.completedGoals': 'Completed Goals',
    'habits.completedOn': 'Completed',
  },
  de: {
    // Navigation & Tabs
    'nav.weekPlanner': 'Wochenplaner',
    'nav.recipes': 'Rezepte',
    'nav.dashboard': 'Dashboard',
    'nav.tasks': 'Aufgaben',
    'nav.calendar': 'Kalender',
    'nav.notes': 'Notizen',
    'nav.habits': 'Gewohnheiten',
    'nav.contacts': 'Kontakte',
    'nav.contracts': 'Verträge',
    'nav.family': 'Familie',
    'nav.settings': 'Einstellungen',
    'nav.assistant': 'Assistent',
    'nav.chat': 'Chat',
    'nav.calls': 'Anrufe',
    'nav.projects': 'Projekte',
    'nav.activity': 'Aktivität',
    'nav.admin': 'Admin',
    'nav.search': 'Suche',
    'nav.todayFocus': 'Heute im Fokus',
    'nav.focusMode': 'Fokus-Modus',
    'nav.weeklyReview': 'Wochenrückblick',
    'nav.voiceMode': 'Sprachmodus',
    'nav.signOut': 'Abmelden',
    'nav.main': 'Hauptmenü',
    'nav.productivity': 'Produktivität',
    
    // Meal Planning
    'meals.generateShoppingList': 'Einkaufsliste erstellen',
    'meals.addRecipe': 'Rezept hinzufügen',
    'meals.addMeal': 'Hinzufügen',
    'meals.noMeals': 'Keine Mahlzeiten',
    'meals.servings': 'Portionen',
    'meals.mealPlanned': 'Mahlzeit geplant',
    'meals.mealsPlanned': 'Mahlzeiten geplant',
    'meals.removeMeal': 'Mahlzeit entfernen',
    'meals.dragToMove': 'Ziehen zum Verschieben',
    'meals.mealDetails': 'Mahlzeit Details',
    'meals.recipe': 'Rezept',
    'meals.notes': 'Notizen',
    'meals.noNotes': 'Keine Notizen',
    'meals.viewRecipe': 'Rezept anzeigen',
    'meals.prepTime': 'Vorbereitungszeit',
    'meals.cookTime': 'Kochzeit',
    'meals.minutes': 'Min',
    'meals.dropHere': 'Hier ablegen',
    
    // Meal Types
    'mealType.breakfast': 'Frühstück',
    'mealType.lunch': 'Mittagessen',
    'mealType.dinner': 'Abendessen',
    'mealType.snack': 'Snack',
    
    // Days
    'day.mon': 'Mo',
    'day.tue': 'Di',
    'day.wed': 'Mi',
    'day.thu': 'Do',
    'day.fri': 'Fr',
    'day.sat': 'Sa',
    'day.sun': 'So',
    
    // Common
    'common.save': 'Speichern',
    'common.cancel': 'Abbrechen',
    'common.delete': 'Löschen',
    'common.edit': 'Bearbeiten',
    'common.add': 'Hinzufügen',
    'common.loading': 'Laden...',
    'common.language': 'Sprache',
    'common.english': 'Englisch',
    'common.german': 'Deutsch',
    'common.search': 'Suchen',
    'common.filter': 'Filtern',
    'common.all': 'Alle',
    'common.today': 'Heute',
    'common.tomorrow': 'Morgen',
    'common.yesterday': 'Gestern',
    'common.thisWeek': 'Diese Woche',
    'common.completed': 'Abgeschlossen',
    'common.pending': 'Ausstehend',
    'common.overdue': 'Überfällig',
    'common.priority': 'Priorität',
    'common.dueDate': 'Fälligkeitsdatum',
    'common.category': 'Kategorie',
    'common.description': 'Beschreibung',
    'common.title': 'Titel',
    'common.name': 'Name',
    'common.email': 'E-Mail',
    'common.phone': 'Telefon',
    'common.address': 'Adresse',
    'common.notes': 'Notizen',
    'common.status': 'Status',
    'common.actions': 'Aktionen',
    'common.view': 'Ansehen',
    'common.close': 'Schließen',
    'common.confirm': 'Bestätigen',
    'common.back': 'Zurück',
    'common.next': 'Weiter',
    'common.previous': 'Vorherige',
    'common.new': 'Neu',
    'common.create': 'Erstellen',
    'common.update': 'Aktualisieren',
    'common.remove': 'Entfernen',
    
    // Recipe Dialog
    'recipe.name': 'Rezeptname',
    'recipe.description': 'Beschreibung',
    'recipe.category': 'Kategorie',
    'recipe.servings': 'Portionen',
    'recipe.prepTime': 'Vorbereitungszeit (Minuten)',
    'recipe.cookTime': 'Kochzeit (Minuten)',
    'recipe.instructions': 'Zubereitung',
    'recipe.ingredients': 'Zutaten',
    'recipe.addRecipe': 'Rezept hinzufügen',
    'recipe.editRecipe': 'Rezept bearbeiten',
    'recipe.noDetails': 'Keine Rezeptdetails verfügbar.',
    'recipe.notFound': 'Rezept nicht gefunden.',
    'recipe.other': 'Sonstiges',
    'recipe.cookingMode': 'Kochmodus',
    'recipe.step': 'Schritt',
    'recipe.of': 'von',
    'recipe.previous': 'Zurück',
    'recipe.next': 'Weiter',
    'recipe.done': 'Fertig',
    'recipe.startCooking': 'Kochen starten',
    
    // Add Meal Dialog
    'addMeal.title': 'Mahlzeit hinzufügen',
    'addMeal.date': 'Datum',
    'addMeal.mealType': 'Mahlzeit',
    'addMeal.selectRecipe': 'Rezept auswählen',
    'addMeal.orCustomMeal': 'Oder eigene Mahlzeit eingeben',
    'addMeal.customMealName': 'Name der Mahlzeit',
    'addMeal.servings': 'Portionen',
    'addMeal.notes': 'Notizen (optional)',
    
    // Dashboard
    'dashboard.title': 'Produktivitäts-Dashboard',
    'dashboard.subtitle': 'Verfolge deinen Fortschritt und Einblicke',
    'dashboard.thisWeek': 'Diese Woche',
    'dashboard.thisMonth': 'Dieser Monat',
    'dashboard.streak': 'Serie',
    'dashboard.peakHours': 'Spitzenzeiten',
    'dashboard.tasksCompleted': 'Aufgaben erledigt',
    'dashboard.consecutiveDays': 'aufeinanderfolgende Tage',
    'dashboard.mostProductive': 'am produktivsten',
    'dashboard.categoryBreakdown': 'Kategorieübersicht',
    'dashboard.productivityByHour': 'Produktivität nach Stunde',
    'dashboard.upcomingDeadlines': 'Anstehende Fristen (Nächste 7 Tage)',
    'dashboard.noDeadlines': 'Keine anstehenden Fristen',
    'dashboard.noTasks': 'Keine Aufgaben',
    'dashboard.completionRate': 'Abschlussrate',
    'dashboard.business': 'Geschäftlich',
    'dashboard.personal': 'Persönlich',
    'dashboard.family': 'Familie',
    'dashboard.more': 'mehr',
    'dashboard.welcome': 'Willkommen',
    'dashboard.overview': 'Übersicht',
    'dashboard.tasksToday': 'Aufgaben heute',
    'dashboard.upcomingEvents': 'Anstehende Termine',
    'dashboard.recentActivity': 'Letzte Aktivität',
    'dashboard.quickActions': 'Schnellaktionen',
    'dashboard.statistics': 'Statistiken',
    'dashboard.progress': 'Fortschritt',
    
    // Tasks
    'tasks.title': 'Aufgaben',
    'tasks.addTask': 'Aufgabe hinzufügen',
    'tasks.newTask': 'Neue Aufgabe',
    'tasks.editTask': 'Aufgabe bearbeiten',
    'tasks.deleteTask': 'Aufgabe löschen',
    'tasks.markComplete': 'Als erledigt markieren',
    'tasks.markIncomplete': 'Als unerledigt markieren',
    'tasks.noTasks': 'Keine Aufgaben',
    'tasks.allCompleted': 'Alle Aufgaben erledigt!',
    'tasks.dueToday': 'Heute fällig',
    'tasks.overdue': 'Überfällig',
    'tasks.upcoming': 'Anstehend',
    'tasks.completed': 'Erledigt',
    'tasks.highPriority': 'Hohe Priorität',
    'tasks.mediumPriority': 'Mittlere Priorität',
    'tasks.lowPriority': 'Niedrige Priorität',
    
    // Calendar
    'calendar.title': 'Kalender',
    'calendar.today': 'Heute',
    'calendar.month': 'Monat',
    'calendar.week': 'Woche',
    'calendar.day': 'Tag',
    'calendar.addEvent': 'Termin hinzufügen',
    'calendar.editEvent': 'Termin bearbeiten',
    'calendar.deleteEvent': 'Termin löschen',
    'calendar.noEvents': 'Keine Termine',
    'calendar.allDay': 'Ganztägig',
    
    // Settings
    'settings.title': 'Einstellungen',
    'settings.profile': 'Profil',
    'settings.account': 'Konto',
    'settings.preferences': 'Voreinstellungen',
    'settings.notifications': 'Benachrichtigungen',
    'settings.appearance': 'Erscheinungsbild',
    'settings.language': 'Sprache',
    'settings.theme': 'Design',
    'settings.dark': 'Dunkel',
    'settings.light': 'Hell',
    'settings.darkMode': 'Dunkelmodus',
    'settings.lightMode': 'Hellmodus',
    'settings.systemMode': 'System',
    'settings.save': 'Einstellungen speichern',
    'settings.saved': 'Einstellungen gespeichert',
    'settings.accentColor': 'Akzentfarbe',
    'settings.taskReminders': 'Aufgabenerinnerungen',
    'settings.taskRemindersDesc': 'Benachrichtigung vor Aufgabenfristen',
    'settings.calendarAlerts': 'Kalenderbenachrichtigungen',
    'settings.calendarAlertsDesc': 'Erinnerungen vor geplanten Terminen',
    'settings.reminderTime': 'Erinnerungszeit',
    'settings.minutesBefore': 'Minuten vorher',
    'settings.defaultCategory': 'Standard-Aufgabenkategorie',
    'settings.defaultPriority': 'Standard-Aufgabenpriorität',
    'settings.defaults': 'Standards',
    'settings.team': 'Team',
    
    // Contacts
    'contacts.title': 'Kontakte',
    'contacts.addContact': 'Kontakt hinzufügen',
    'contacts.editContact': 'Kontakt bearbeiten',
    'contacts.deleteContact': 'Kontakt löschen',
    'contacts.noContacts': 'Keine Kontakte',
    'contacts.searchContacts': 'Kontakte suchen...',
    
    // Habits
    'habits.title': 'Gewohnheiten',
    'habits.addHabit': 'Gewohnheit hinzufügen',
    'habits.editHabit': 'Gewohnheit bearbeiten',
    'habits.deleteHabit': 'Gewohnheit löschen',
    'habits.streak': 'Serie',
    'habits.completed': 'Abgeschlossen',
    'habits.noHabits': 'Keine Gewohnheiten',
    'habits.daily': 'Täglich',
    'habits.weekly': 'Wöchentlich',
    
    // Projects
    'projects.title': 'Projekte',
    'projects.addProject': 'Projekt hinzufügen',
    'projects.editProject': 'Projekt bearbeiten',
    'projects.deleteProject': 'Projekt löschen',
    'projects.noProjects': 'Keine Projekte',
    'projects.archived': 'Archiviert',
    'projects.active': 'Aktiv',
    
    // Task Categories & Priorities
    'category.personal': 'Persönlich',
    'category.business': 'Geschäftlich',
    'category.family': 'Familie',
    'category.all': 'Alle',
    'category.shared': 'Geteilt',
    'priority.low': 'Niedrig',
    'priority.medium': 'Mittel',
    'priority.high': 'Hoch',
    
    // Task List
    'taskList.addTask': 'Aufgabe hinzufügen',
    'taskList.newTask': 'Neue Aufgabe...',
    'taskList.overdue': 'Überfällig',
    'taskList.setDueDate': 'Fälligkeitsdatum setzen',
    'taskList.clearDueDate': 'Fälligkeitsdatum löschen',
    'taskList.deleteSelected': 'Ausgewählte löschen',
    'taskList.cancel': 'Abbrechen',
    'taskList.noTasks': 'Noch keine Aufgaben',
    'taskList.startAdding': 'Beginne Aufgaben hinzuzufügen!',
    'taskList.completed': 'Erledigt',
    'taskList.editTask': 'Aufgabe bearbeiten',
    'taskList.addSubtask': 'Unteraufgabe hinzufügen',
    'taskList.sharedBy': 'Geteilt von',
    'taskList.event': 'Termin',
    'taskList.task': 'Aufgabe',
    
    // Time Filters
    'time.all': 'Alle',
    'time.today': 'Heute',
    'time.week': 'Woche',
    'time.month': 'Monat',
    'time.noDate': 'Ohne Datum',
    
    // Calendar Panel
    'calendar.agenda': 'Terminübersicht',
    'calendar.import': 'Importieren',
    'calendar.invalidFile': 'Ungültige Datei',
    'calendar.invalidFileDesc': 'Bitte laden Sie eine gültige .ics Kalenderdatei hoch.',
    'calendar.noEventsFound': 'Keine Termine gefunden',
    'calendar.noEventsFoundDesc': 'Die Datei enthält keine gültigen Termine.',
    'calendar.importSuccess': 'Import erfolgreich',
    'calendar.importedEvents': '{count} Termin(e) importiert.',
    'calendar.importFailed': 'Import fehlgeschlagen',
    'calendar.importFailedDesc': 'Kalenderdatei konnte nicht gelesen werden. Bitte Format prüfen.',
    'calendar.updatedSuccess': 'Erfolgreich aktualisiert',
    'calendar.deletedSuccess': 'Erfolgreich gelöscht',
    'calendar.noUpcoming': 'Keine anstehenden Termine oder Aufgaben',
    'calendar.tasksWithDueDates': 'Aufgaben mit Fälligkeitsdatum erscheinen hier',
    'calendar.importIcs': '.ics importieren',
    'calendar.scheduleSomething': 'Etwas planen',
    'calendar.sharedBy': 'Geteilt von',
    
    // Notes Panel
    'notes.title': 'Notizen',
    'notes.newNote': 'Neue Notiz',
    'notes.searchNotes': 'Notizen suchen...',
    'notes.noNotes': 'Noch keine Notizen',
    'notes.createFirst': 'Erstelle deine erste Notiz',
    'notes.noContent': 'Kein Inhalt',
    
    // Habits Panel
    'habits.habitsAndGoals': 'Gewohnheiten & Ziele',
    'habits.todaysProgress': 'Heutiger Fortschritt',
    'habits.addNewHabit': 'Neue Gewohnheit hinzufügen',
    'habits.noHabitsYet': 'Noch keine Gewohnheiten',
    'habits.createFirstHabit': 'Erstelle deine erste Gewohnheit',
    'habits.goals': 'Ziele',
    'habits.addNewGoal': 'Neues Ziel hinzufügen',
    'habits.noGoalsYet': 'Noch keine Ziele',
    'habits.setGoal': 'Setze ein Ziel um deinen Fortschritt zu verfolgen',
    'habits.target': 'Ziel',
    'habits.completedGoals': 'Erledigte Ziele',
    'habits.completedOn': 'Erledigt am',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('app-language');
    return (saved as Language) || 'de';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('app-language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
