import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'de';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation & Tabs
    'nav.weekPlanner': 'Week Planner',
    'nav.recipes': 'Recipes',
    'nav.dashboard': 'Dashboard',
    'nav.tasks': 'Tasks',
    'nav.calendar': 'Calendar',
    'nav.notes': 'Notes',
    'nav.habits': 'Habits',
    'nav.contacts': 'Contacts',
    'nav.contracts': 'Contracts',
    'nav.social': 'Social',
    'nav.family': 'Family',
    'nav.settings': 'Settings',
    'nav.assistant': 'Assistant',
    'nav.chat': 'Chat',
    'nav.calls': 'Calls',
    'nav.projects': 'Projects',
    'nav.activity': 'Activity',
    'nav.admin': 'Admin',
    'nav.search': 'Search',
    'nav.todayFocus': "Today's Focus",
    'nav.focusMode': 'Focus Mode',
    'nav.weeklyReview': 'Weekly Review',
    'nav.voiceMode': 'Voice Mode',
    'nav.signOut': 'Sign Out',
    'nav.main': 'Main',
    'nav.productivity': 'Productivity',
    'nav.islam': 'Islam',
    'nav.properties': 'Properties',
    'nav.startups': 'Startups',
    'nav.news': 'Tech News',
    
    // Meal Planning
    'meals.generateShoppingList': 'Generate Shopping List',
    'meals.addRecipe': 'Add Recipe',
    'meals.addMeal': 'Add',
    'meals.noMeals': 'No meals',
    'meals.servings': 'servings',
    'meals.mealPlanned': 'meal planned',
    'meals.mealsPlanned': 'meals planned',
    'meals.removeMeal': 'Remove meal',
    'meals.dragToMove': 'Drag to move',
    'meals.mealDetails': 'Meal Details',
    'meals.recipe': 'Recipe',
    'meals.notes': 'Notes',
    'meals.noNotes': 'No notes',
    'meals.viewRecipe': 'View Recipe',
    'meals.prepTime': 'Prep time',
    'meals.cookTime': 'Cook time',
    'meals.minutes': 'min',
    'meals.dropHere': 'Drop here',
    
    // Meal Types
    'mealType.breakfast': 'Breakfast',
    'mealType.lunch': 'Lunch',
    'mealType.dinner': 'Dinner',
    'mealType.snack': 'Snack',
    
    // Days
    'day.mon': 'Mon',
    'day.tue': 'Tue',
    'day.wed': 'Wed',
    'day.thu': 'Thu',
    'day.fri': 'Fri',
    'day.sat': 'Sat',
    'day.sun': 'Sun',
    
    // Common
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.add': 'Add',
    'common.loading': 'Loading...',
    'common.language': 'Language',
    'common.english': 'English',
    'common.german': 'German',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.all': 'All',
    'common.today': 'Today',
    'common.tomorrow': 'Tomorrow',
    'common.yesterday': 'Yesterday',
    'common.thisWeek': 'This Week',
    'common.completed': 'Completed',
    'common.pending': 'Pending',
    'common.overdue': 'Overdue',
    'common.priority': 'Priority',
    'common.dueDate': 'Due Date',
    'common.category': 'Category',
    'common.description': 'Description',
    'common.title': 'Title',
    'common.name': 'Name',
    'common.email': 'Email',
    'common.phone': 'Phone',
    'common.address': 'Address',
    'common.notes': 'Notes',
    'common.status': 'Status',
    'common.actions': 'Actions',
    'common.view': 'View',
    'common.close': 'Close',
    'common.confirm': 'Confirm',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.new': 'New',
    'common.create': 'Create',
    'common.update': 'Update',
    'common.remove': 'Remove',
    
    // Recipe Dialog
    'recipe.name': 'Recipe Name',
    'recipe.description': 'Description',
    'recipe.category': 'Category',
    'recipe.servings': 'Servings',
    'recipe.prepTime': 'Prep Time (minutes)',
    'recipe.cookTime': 'Cook Time (minutes)',
    'recipe.instructions': 'Instructions',
    'recipe.ingredients': 'Ingredients',
    'recipe.addRecipe': 'Add Recipe',
    'recipe.editRecipe': 'Edit Recipe',
    'recipe.noDetails': 'No recipe details available.',
    'recipe.notFound': 'Recipe not found.',
    'recipe.other': 'Other',
    'recipe.cookingMode': 'Cooking Mode',
    'recipe.step': 'Step',
    'recipe.of': 'of',
    'recipe.previous': 'Previous',
    'recipe.next': 'Next',
    'recipe.done': 'Done',
    'recipe.startCooking': 'Start Cooking',
    
    // Add Meal Dialog
    'addMeal.title': 'Add Meal',
    'addMeal.date': 'Date',
    'addMeal.mealType': 'Meal Type',
    'addMeal.selectRecipe': 'Select a recipe',
    'addMeal.orCustomMeal': 'Or enter custom meal name',
    'addMeal.customMealName': 'Custom Meal Name',
    'addMeal.servings': 'Servings',
    'addMeal.notes': 'Notes (optional)',
    
    // Dashboard
    'dashboard.title': 'Productivity Dashboard',
    'dashboard.subtitle': 'Track your progress and insights',
    'dashboard.thisWeek': 'This Week',
    'dashboard.thisMonth': 'This Month',
    'dashboard.streak': 'Streak',
    'dashboard.peakHours': 'Peak Hours',
    'dashboard.tasksCompleted': 'tasks completed',
    'dashboard.consecutiveDays': 'consecutive days',
    'dashboard.mostProductive': 'most productive',
    'dashboard.categoryBreakdown': 'Category Breakdown',
    'dashboard.productivityByHour': 'Productivity by Hour',
    'dashboard.upcomingDeadlines': 'Upcoming Deadlines (Next 7 Days)',
    'dashboard.noDeadlines': 'No upcoming deadlines',
    'dashboard.noTasks': 'No tasks',
    'dashboard.completionRate': 'Completion Rate',
    'dashboard.business': 'Business',
    'dashboard.personal': 'Personal',
    'dashboard.family': 'Family',
    'dashboard.more': 'more',
    'dashboard.welcome': 'Welcome',
    'dashboard.overview': 'Overview',
    'dashboard.tasksToday': 'Tasks Today',
    'dashboard.upcomingEvents': 'Upcoming Events',
    'dashboard.recentActivity': 'Recent Activity',
    'dashboard.quickActions': 'Quick Actions',
    'dashboard.statistics': 'Statistics',
    'dashboard.progress': 'Progress',
    
    // Tasks
    'tasks.title': 'Tasks',
    'tasks.addTask': 'Add Task',
    'tasks.newTask': 'New Task',
    'tasks.editTask': 'Edit Task',
    'tasks.deleteTask': 'Delete Task',
    'tasks.markComplete': 'Mark Complete',
    'tasks.markIncomplete': 'Mark Incomplete',
    'tasks.noTasks': 'No tasks',
    'tasks.allCompleted': 'All tasks completed!',
    'tasks.dueToday': 'Due Today',
    'tasks.overdue': 'Overdue',
    'tasks.upcoming': 'Upcoming',
    'tasks.completed': 'Completed',
    'tasks.highPriority': 'High Priority',
    'tasks.mediumPriority': 'Medium Priority',
    'tasks.lowPriority': 'Low Priority',
    
    // Calendar
    'calendar.title': 'Calendar',
    'calendar.today': 'Today',
    'calendar.month': 'Month',
    'calendar.week': 'Week',
    'calendar.day': 'Day',
    'calendar.addEvent': 'Add Event',
    'calendar.editEvent': 'Edit Event',
    'calendar.deleteEvent': 'Delete Event',
    'calendar.noEvents': 'No events',
    'calendar.allDay': 'All Day',
    
    // Settings
    'settings.title': 'Settings',
    'settings.profile': 'Profile',
    'settings.account': 'Account',
    'settings.preferences': 'Preferences',
    'settings.notifications': 'Notifications',
    'settings.appearance': 'Appearance',
    'settings.language': 'Language',
    'settings.theme': 'Theme',
    'settings.dark': 'Dark',
    'settings.light': 'Light',
    'settings.darkMode': 'Dark Mode',
    'settings.lightMode': 'Light Mode',
    'settings.systemMode': 'System',
    'settings.save': 'Save Settings',
    'settings.saved': 'Settings saved',
    'settings.accentColor': 'Accent Color',
    'settings.taskReminders': 'Task Reminders',
    'settings.taskRemindersDesc': 'Get notified before task deadlines',
    'settings.calendarAlerts': 'Calendar Alerts',
    'settings.calendarAlertsDesc': 'Reminders before scheduled events',
    'settings.reminderTime': 'Reminder Time',
    'settings.minutesBefore': 'minutes before',
    'settings.defaultCategory': 'Default Task Category',
    'settings.defaultPriority': 'Default Task Priority',
    'settings.defaults': 'Defaults',
    'settings.team': 'Team',
    
    // Contacts
    'contacts.title': 'Contacts',
    'contacts.addContact': 'Add Contact',
    'contacts.editContact': 'Edit Contact',
    'contacts.deleteContact': 'Delete Contact',
    'contacts.noContacts': 'No contacts',
    'contacts.searchContacts': 'Search contacts...',
    
    // Habits
    'habits.title': 'Habits',
    'habits.addHabit': 'Add Habit',
    'habits.editHabit': 'Edit Habit',
    'habits.deleteHabit': 'Delete Habit',
    'habits.streak': 'Streak',
    'habits.completed': 'Completed',
    'habits.noHabits': 'No habits',
    'habits.daily': 'Daily',
    'habits.weekly': 'Weekly',
    
    // Projects
    'projects.title': 'Projects',
    'projects.addProject': 'Add Project',
    'projects.editProject': 'Edit Project',
    'projects.deleteProject': 'Delete Project',
    'projects.noProjects': 'No projects',
    'projects.archived': 'Archived',
    'projects.active': 'Active',
    
    // Task Categories & Priorities
    'category.personal': 'Personal',
    'category.business': 'Business',
    'category.family': 'Family',
    'category.all': 'All',
    'category.shared': 'Shared',
    'priority.low': 'Low',
    'priority.medium': 'Medium',
    'priority.high': 'High',
    
    // Task List
    'taskList.addTask': 'Add Task',
    'taskList.newTask': 'New task...',
    'taskList.overdue': 'Overdue',
    'taskList.setDueDate': 'Set due date',
    'taskList.clearDueDate': 'Clear due date',
    'taskList.deleteSelected': 'Delete selected',
    'taskList.cancel': 'Cancel',
    'taskList.noTasks': 'No tasks yet',
    'taskList.startAdding': 'Start adding tasks to get productive!',
    'taskList.completed': 'Completed',
    'taskList.editTask': 'Edit task',
    'taskList.addSubtask': 'Add subtask',
    'taskList.sharedBy': 'Shared by',
    'taskList.event': 'Event',
    'taskList.task': 'Task',
    
    // Time Filters
    'time.all': 'All',
    'time.today': 'Today',
    'time.week': 'Week',
    'time.month': 'Month',
    'time.noDate': 'No Date',
    
    // Calendar Panel
    'calendar.agenda': 'Agenda',
    'calendar.import': 'Import',
    'calendar.invalidFile': 'Invalid File',
    'calendar.invalidFileDesc': 'Please upload a valid .ics calendar file.',
    'calendar.noEventsFound': 'No Events Found',
    'calendar.noEventsFoundDesc': 'The file does not contain any valid events.',
    'calendar.importSuccess': 'Import Successful',
    'calendar.importedEvents': 'Imported {count} event(s).',
    'calendar.importFailed': 'Import Failed',
    'calendar.importFailedDesc': 'Failed to parse the calendar file. Please check the format.',
    'calendar.updatedSuccess': 'Updated successfully',
    'calendar.deletedSuccess': 'Deleted successfully',
    'calendar.noUpcoming': 'No upcoming events or tasks',
    'calendar.tasksWithDueDates': 'Tasks with due dates will appear here',
    'calendar.importIcs': 'Import .ics',
    'calendar.scheduleSomething': 'Schedule something',
    'calendar.sharedBy': 'Shared by',
    
    // Notes Panel
    'notes.title': 'Notes',
    'notes.newNote': 'New Note',
    'notes.searchNotes': 'Search notes...',
    'notes.noNotes': 'No notes yet',
    'notes.createFirst': 'Create your first note',
    'notes.noContent': 'No content',
    
    // Habits Panel
    'habits.habitsAndGoals': 'Habits & Goals',
    'habits.todaysProgress': "Today's Progress",
    'habits.addNewHabit': 'Add New Habit',
    'habits.noHabitsYet': 'No habits yet',
    'habits.createFirstHabit': 'Create your first habit to start tracking',
    'habits.goals': 'Goals',
    'habits.addNewGoal': 'Add New Goal',
    'habits.noGoalsYet': 'No goals yet',
    'habits.setGoal': 'Set a goal to track your progress',
    'habits.target': 'Target',
    'habits.completedGoals': 'Completed Goals',
    'habits.completedOn': 'Completed',
    
    // Add Habit Dialog
    'addHabit.title': 'Add New Habit',
    'addHabit.habitName': 'Habit Name',
    'addHabit.habitNamePlaceholder': 'e.g., Drink 8 glasses of water',
    'addHabit.description': 'Description (optional)',
    'addHabit.descriptionPlaceholder': 'Why is this habit important to you?',
    'addHabit.icon': 'Icon',
    'addHabit.color': 'Color',
    'addHabit.frequency': 'Frequency',
    'addHabit.targetPerDay': 'Target per day',
    'addHabit.daysOfWeek': 'Days of Week',
    'addHabit.daily': 'Daily',
    'addHabit.weekly': 'Weekly',
    'addHabit.custom': 'Custom Days',
    'addHabit.creating': 'Creating...',
    'addHabit.createHabit': 'Create Habit',
    
    // Add Goal Dialog
    'addGoal.title': 'Add New Goal',
    'addGoal.goalName': 'Goal Name',
    'addGoal.goalNamePlaceholder': 'e.g., Read 12 books this year',
    'addGoal.description': 'Description (optional)',
    'addGoal.descriptionPlaceholder': 'What will achieving this goal mean to you?',
    'addGoal.icon': 'Icon',
    'addGoal.color': 'Color',
    'addGoal.current': 'Current',
    'addGoal.target': 'Target',
    'addGoal.unit': 'Unit',
    'addGoal.targetDate': 'Target Date (optional)',
    'addGoal.pickDate': 'Pick a date',
    'addGoal.creating': 'Creating...',
    'addGoal.createGoal': 'Create Goal',
    
    // Edit Task Modal
    'editTask.title': 'Edit Task',
    'editTask.taskTitle': 'Title',
    'editTask.taskTitlePlaceholder': 'Task title',
    'editTask.description': 'Description (Markdown supported)',
    'editTask.descriptionPlaceholder': 'Optional description - supports **bold**, *italic*, - lists...',
    'editTask.project': 'Project',
    'editTask.noProject': 'No project',
    'editTask.selectProject': 'Select project',
    'editTask.mainResponsible': 'Main Responsible',
    'editTask.secondaryResponsible': 'Secondary Responsible',
    'editTask.notAssigned': 'Not assigned',
    'editTask.priority': 'Priority',
    'editTask.category': 'Category',
    'editTask.dueDateTime': 'Due Date & Time',
    'editTask.noDueDate': 'No due date',
    'editTask.clearDueDate': 'Clear due date',
    'editTask.recurrence': 'Recurrence',
    'editTask.noRecurrence': 'No recurrence',
    'editTask.dontRepeat': "Don't repeat",
    'editTask.customRecurrence': 'Custom Recurrence',
    'editTask.every': 'Every',
    'editTask.onDays': 'On days',
    'editTask.endDate': 'End Date (optional)',
    'editTask.apply': 'Apply',
    'editTask.reminder': 'Reminder',
    'editTask.noReminder': 'No reminder',
    'editTask.checklist': 'Checklist',
    'editTask.addItem': 'Add item...',
    'editTask.aiBreakdown': 'AI Breakdown',
    'editTask.saveChanges': 'Save Changes',
    'editTask.deleteTask': 'Delete Task',
    
    // Reminder Options
    'reminder.none': 'No reminder',
    'reminder.15min': '15 minutes before',
    'reminder.30min': '30 minutes before',
    'reminder.1hour': '1 hour before',
    'reminder.2hours': '2 hours before',
    'reminder.1day': '1 day before',
    'reminder.2days': '2 days before',
    'reminder.1week': '1 week before',
    
    // Recurrence Frequency
    'frequency.daily': 'Day(s)',
    'frequency.weekly': 'Week(s)',
    'frequency.monthly': 'Month(s)',
    'frequency.yearly': 'Year(s)',
    
    // Weekdays
    'weekday.sun': 'Sun',
    'weekday.mon': 'Mon',
    'weekday.tue': 'Tue',
    'weekday.wed': 'Wed',
    'weekday.thu': 'Thu',
    'weekday.fri': 'Fri',
    'weekday.sat': 'Sat',
    
    // Contacts Panel
    'contacts.manageNetwork': 'Manage your network',
    'contacts.personal': 'Personal',
    'contacts.business': 'Business',
    'contacts.due': 'Due',
    'contacts.name': 'Name',
    'contacts.email': 'Email',
    'contacts.phone': 'Phone',
    'contacts.company': 'Company',
    'contacts.role': 'Role',
    'contacts.type': 'Type',
    'contacts.tier': 'Tier',
    'contacts.level': 'Level',
    'contacts.relationship': 'Relationship',
    'contacts.contactFrequency': 'Contact Frequency (days)',
    'contacts.notes': 'Notes',
    'contacts.tags': 'Tags (comma-separated)',
    'contacts.socialLinks': 'Social Links',
    'contacts.location': 'Location',
    'contacts.country': 'Country',
    'contacts.city': 'City',
    'contacts.save': 'Save',
    'contacts.confirmDelete': 'Confirm Delete',
    'contacts.confirmDeleteDesc': 'Are you sure you want to delete this contact? This action cannot be undone.',
    'contacts.contactUpdated': 'Contact updated',
    'contacts.contactAdded': 'Contact added',
    'contacts.contactDeleted': 'Contact deleted',
    'contacts.markedContacted': 'Marked as contacted',
    'contacts.selectTier': 'Select tier',
    'contacts.selectLevel': 'Select level',
    'contacts.selectRelationship': 'Select relationship',
    
    // Personal Tiers
    'tier.family': 'Family',
    'tier.closeFriend': 'Close Friend',
    'tier.friend': 'Friend',
    'tier.acquaintance': 'Acquaintance',
    
    // Business Levels
    'level.veryWell': 'Know Very Well',
    'level.well': 'Know Well',
    'level.barely': 'Barely Know',
    'level.notContacted': 'Not Contacted Yet',
    
    // Contracts Panel
    'contracts.title': 'Contracts & Subscriptions',
    'contracts.subtitle': 'Manage your contracts, subscriptions, and recurring payments',
    'contracts.addContract': 'Add Contract',
    'contracts.editContract': 'Edit Contract',
    'contracts.deleteContract': 'Delete Contract',
    'contracts.monthlyCost': 'Monthly Cost',
    'contracts.yearlyCost': 'Yearly Cost',
    'contracts.activeContracts': 'Active Contracts',
    'contracts.expiringSoon': 'Expiring Soon',
    'contracts.searchContracts': 'Search contracts...',
    'contracts.noContractsSearch': 'No contracts match your search',
    'contracts.noContracts': 'No contracts yet. Add your first contract!',
    'contracts.cancellationDeadlines': 'Upcoming Cancellation Deadlines',
    'contracts.cancelBy': 'Cancel by',
    'contracts.contract': 'Contract',
    'contracts.provider': 'Provider',
    'contracts.category': 'Category',
    'contracts.cost': 'Cost',
    'contracts.renewal': 'Renewal',
    'contracts.status': 'Status',
    'contracts.actions': 'Actions',
    'contracts.active': 'Active',
    'contracts.inactive': 'Inactive',
    'contracts.auto': 'Auto',
    'contracts.all': 'All',
    'contracts.confirmDeleteTitle': 'Delete Contract?',
    'contracts.confirmDeleteDesc': 'Are you sure you want to delete this contract? This action cannot be undone.',
    
    // Family Panel
    'family.title': 'Family Hub',
    'family.subtitle': 'Manage your family, household tasks, and events',
    'family.members': 'Members',
    'family.kids': 'Kids',
    'family.tasks': 'Tasks',
    'family.meals': 'Meals',
    'family.shopping': 'Shop',
    'family.budget': 'Budget',
    'family.health': 'Health',
    'family.docs': 'Docs',
    'family.calendar': 'Calendar',
    
    // Cooking Panel
    'cooking.title': 'Cooking & Food',
    'cooking.subtitle': 'Plan your meals and manage recipes',
    'nav.cooking': 'Cooking',
    
    // Mobile Navigation
    'nav.dori': 'Dori',
    'nav.allTasks': 'All Tasks',
    'nav.business': 'Business',
    'nav.personal': 'Personal',
    'nav.sharedWithMe': 'Shared with me',
    'nav.familyHub': 'Family Hub',
    
    // Islam Panel
    'islam.title': 'Islam',
    'islam.prayer': 'Prayer',
    'islam.qibla': 'Qibla',
    'islam.quran': 'Quran',
    'islam.hifz': 'Hifz',
    'islam.hadith': 'Hadith',
    'islam.duas': 'Duas',
    'islam.calendar': 'Calendar',
    'islam.qiblaFinder': 'Qibla Finder',
    'islam.findQibla': 'Find Qibla',
    'islam.loading': 'Loading...',
    'islam.yourLocation': 'Your Location',
    'islam.qiblaDirection': 'Qibla Direction',
    'islam.locationNeeded': 'Location access needed',
    'islam.enableLocation': 'Enable Location',
    'islam.searchSurah': 'Search surah...',
    'islam.verses': 'verses',
    'islam.selectSurah': 'Select a surah to read',
    'islam.readQuran': 'Read the Holy Quran',
    'islam.duaCollection': 'Dua Collection',
    'islam.allCategories': 'All Categories',
    'islam.islamicCalendar': 'Islamic Calendar',
    'islam.hijriDate': 'Hijri Date',
    'islam.today': 'Today',
    
    // Auth
    'auth.displayName': 'Display Name',
    'auth.yourName': 'Your name',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.signIn': 'Sign In',
    'auth.createAccount': 'Create Account',
    'auth.dontHaveAccount': "Don't have an account? Sign up",
    'auth.alreadyHaveAccount': 'Already have an account? Sign in',
    'auth.loginFailed': 'Login Failed',
    'auth.welcomeBack': 'Welcome back!',
    'auth.successLogin': 'Successfully logged in.',
    'auth.accountExists': 'Account Exists',
    'auth.emailAlreadyRegistered': 'This email is already registered. Please log in.',
    'auth.signUpFailed': 'Sign Up Failed',
    'auth.accountCreated': 'Account Created!',
    'auth.startUsingApp': 'You can now start using DarAI.',
  },
  de: {
    // Navigation & Tabs
    'nav.weekPlanner': 'Wochenplaner',
    'nav.recipes': 'Rezepte',
    'nav.dashboard': 'Dashboard',
    'nav.tasks': 'Aufgaben',
    'nav.calendar': 'Kalender',
    'nav.notes': 'Notizen',
    'nav.habits': 'Gewohnheiten',
    'nav.contacts': 'Kontakte',
    'nav.contracts': 'Verträge',
    'nav.social': 'Sozial',
    'nav.family': 'Familie',
    'nav.settings': 'Einstellungen',
    'nav.assistant': 'Assistent',
    'nav.chat': 'Chat',
    'nav.calls': 'Anrufe',
    'nav.projects': 'Projekte',
    'nav.activity': 'Aktivität',
    'nav.admin': 'Admin',
    'nav.search': 'Suche',
    'nav.todayFocus': 'Heute im Fokus',
    'nav.focusMode': 'Fokus-Modus',
    'nav.weeklyReview': 'Wochenrückblick',
    'nav.voiceMode': 'Sprachmodus',
    'nav.signOut': 'Abmelden',
    'nav.main': 'Hauptmenü',
    'nav.productivity': 'Produktivität',
    'nav.islam': 'Islam',
    'nav.properties': 'Immobilien',
    'nav.startups': 'Startups',
    'nav.news': 'Tech News',
    
    // Meal Planning
    'meals.generateShoppingList': 'Einkaufsliste erstellen',
    'meals.addRecipe': 'Rezept hinzufügen',
    'meals.addMeal': 'Hinzufügen',
    'meals.noMeals': 'Keine Mahlzeiten',
    'meals.servings': 'Portionen',
    'meals.mealPlanned': 'Mahlzeit geplant',
    'meals.mealsPlanned': 'Mahlzeiten geplant',
    'meals.removeMeal': 'Mahlzeit entfernen',
    'meals.dragToMove': 'Ziehen zum Verschieben',
    'meals.mealDetails': 'Mahlzeit Details',
    'meals.recipe': 'Rezept',
    'meals.notes': 'Notizen',
    'meals.noNotes': 'Keine Notizen',
    'meals.viewRecipe': 'Rezept anzeigen',
    'meals.prepTime': 'Vorbereitungszeit',
    'meals.cookTime': 'Kochzeit',
    'meals.minutes': 'Min',
    'meals.dropHere': 'Hier ablegen',
    
    // Meal Types
    'mealType.breakfast': 'Frühstück',
    'mealType.lunch': 'Mittagessen',
    'mealType.dinner': 'Abendessen',
    'mealType.snack': 'Snack',
    
    // Days
    'day.mon': 'Mo',
    'day.tue': 'Di',
    'day.wed': 'Mi',
    'day.thu': 'Do',
    'day.fri': 'Fr',
    'day.sat': 'Sa',
    'day.sun': 'So',
    
    // Common
    'common.save': 'Speichern',
    'common.cancel': 'Abbrechen',
    'common.delete': 'Löschen',
    'common.edit': 'Bearbeiten',
    'common.add': 'Hinzufügen',
    'common.loading': 'Laden...',
    'common.language': 'Sprache',
    'common.english': 'Englisch',
    'common.german': 'Deutsch',
    'common.search': 'Suchen',
    'common.filter': 'Filtern',
    'common.all': 'Alle',
    'common.today': 'Heute',
    'common.tomorrow': 'Morgen',
    'common.yesterday': 'Gestern',
    'common.thisWeek': 'Diese Woche',
    'common.completed': 'Abgeschlossen',
    'common.pending': 'Ausstehend',
    'common.overdue': 'Überfällig',
    'common.priority': 'Priorität',
    'common.dueDate': 'Fälligkeitsdatum',
    'common.category': 'Kategorie',
    'common.description': 'Beschreibung',
    'common.title': 'Titel',
    'common.name': 'Name',
    'common.email': 'E-Mail',
    'common.phone': 'Telefon',
    'common.address': 'Adresse',
    'common.notes': 'Notizen',
    'common.status': 'Status',
    'common.actions': 'Aktionen',
    'common.view': 'Ansehen',
    'common.close': 'Schließen',
    'common.confirm': 'Bestätigen',
    'common.back': 'Zurück',
    'common.next': 'Weiter',
    'common.previous': 'Vorherige',
    'common.new': 'Neu',
    'common.create': 'Erstellen',
    'common.update': 'Aktualisieren',
    'common.remove': 'Entfernen',
    
    // Recipe Dialog
    'recipe.name': 'Rezeptname',
    'recipe.description': 'Beschreibung',
    'recipe.category': 'Kategorie',
    'recipe.servings': 'Portionen',
    'recipe.prepTime': 'Vorbereitungszeit (Minuten)',
    'recipe.cookTime': 'Kochzeit (Minuten)',
    'recipe.instructions': 'Zubereitung',
    'recipe.ingredients': 'Zutaten',
    'recipe.addRecipe': 'Rezept hinzufügen',
    'recipe.editRecipe': 'Rezept bearbeiten',
    'recipe.noDetails': 'Keine Rezeptdetails verfügbar.',
    'recipe.notFound': 'Rezept nicht gefunden.',
    'recipe.other': 'Sonstiges',
    'recipe.cookingMode': 'Kochmodus',
    'recipe.step': 'Schritt',
    'recipe.of': 'von',
    'recipe.previous': 'Zurück',
    'recipe.next': 'Weiter',
    'recipe.done': 'Fertig',
    'recipe.startCooking': 'Kochen starten',
    
    // Add Meal Dialog
    'addMeal.title': 'Mahlzeit hinzufügen',
    'addMeal.date': 'Datum',
    'addMeal.mealType': 'Mahlzeit',
    'addMeal.selectRecipe': 'Rezept auswählen',
    'addMeal.orCustomMeal': 'Oder eigene Mahlzeit eingeben',
    'addMeal.customMealName': 'Name der Mahlzeit',
    'addMeal.servings': 'Portionen',
    'addMeal.notes': 'Notizen (optional)',
    
    // Dashboard
    'dashboard.title': 'Produktivitäts-Dashboard',
    'dashboard.subtitle': 'Verfolge deinen Fortschritt und Einblicke',
    'dashboard.thisWeek': 'Diese Woche',
    'dashboard.thisMonth': 'Dieser Monat',
    'dashboard.streak': 'Serie',
    'dashboard.peakHours': 'Spitzenzeiten',
    'dashboard.tasksCompleted': 'Aufgaben erledigt',
    'dashboard.consecutiveDays': 'aufeinanderfolgende Tage',
    'dashboard.mostProductive': 'am produktivsten',
    'dashboard.categoryBreakdown': 'Kategorieübersicht',
    'dashboard.productivityByHour': 'Produktivität nach Stunde',
    'dashboard.upcomingDeadlines': 'Anstehende Fristen (Nächste 7 Tage)',
    'dashboard.noDeadlines': 'Keine anstehenden Fristen',
    'dashboard.noTasks': 'Keine Aufgaben',
    'dashboard.completionRate': 'Abschlussrate',
    'dashboard.business': 'Geschäftlich',
    'dashboard.personal': 'Persönlich',
    'dashboard.family': 'Familie',
    'dashboard.more': 'mehr',
    'dashboard.welcome': 'Willkommen',
    'dashboard.overview': 'Übersicht',
    'dashboard.tasksToday': 'Aufgaben heute',
    'dashboard.upcomingEvents': 'Anstehende Termine',
    'dashboard.recentActivity': 'Letzte Aktivität',
    'dashboard.quickActions': 'Schnellaktionen',
    'dashboard.statistics': 'Statistiken',
    'dashboard.progress': 'Fortschritt',
    
    // Tasks
    'tasks.title': 'Aufgaben',
    'tasks.addTask': 'Aufgabe hinzufügen',
    'tasks.newTask': 'Neue Aufgabe',
    'tasks.editTask': 'Aufgabe bearbeiten',
    'tasks.deleteTask': 'Aufgabe löschen',
    'tasks.markComplete': 'Als erledigt markieren',
    'tasks.markIncomplete': 'Als unerledigt markieren',
    'tasks.noTasks': 'Keine Aufgaben',
    'tasks.allCompleted': 'Alle Aufgaben erledigt!',
    'tasks.dueToday': 'Heute fällig',
    'tasks.overdue': 'Überfällig',
    'tasks.upcoming': 'Anstehend',
    'tasks.completed': 'Erledigt',
    'tasks.highPriority': 'Hohe Priorität',
    'tasks.mediumPriority': 'Mittlere Priorität',
    'tasks.lowPriority': 'Niedrige Priorität',
    
    // Calendar
    'calendar.title': 'Kalender',
    'calendar.today': 'Heute',
    'calendar.month': 'Monat',
    'calendar.week': 'Woche',
    'calendar.day': 'Tag',
    'calendar.addEvent': 'Termin hinzufügen',
    'calendar.editEvent': 'Termin bearbeiten',
    'calendar.deleteEvent': 'Termin löschen',
    'calendar.noEvents': 'Keine Termine',
    'calendar.allDay': 'Ganztägig',
    
    // Settings
    'settings.title': 'Einstellungen',
    'settings.profile': 'Profil',
    'settings.account': 'Konto',
    'settings.preferences': 'Voreinstellungen',
    'settings.notifications': 'Benachrichtigungen',
    'settings.appearance': 'Erscheinungsbild',
    'settings.language': 'Sprache',
    'settings.theme': 'Design',
    'settings.dark': 'Dunkel',
    'settings.light': 'Hell',
    'settings.darkMode': 'Dunkelmodus',
    'settings.lightMode': 'Hellmodus',
    'settings.systemMode': 'System',
    'settings.save': 'Einstellungen speichern',
    'settings.saved': 'Einstellungen gespeichert',
    'settings.accentColor': 'Akzentfarbe',
    'settings.taskReminders': 'Aufgabenerinnerungen',
    'settings.taskRemindersDesc': 'Benachrichtigung vor Aufgabenfristen',
    'settings.calendarAlerts': 'Kalenderbenachrichtigungen',
    'settings.calendarAlertsDesc': 'Erinnerungen vor geplanten Terminen',
    'settings.reminderTime': 'Erinnerungszeit',
    'settings.minutesBefore': 'Minuten vorher',
    'settings.defaultCategory': 'Standard-Aufgabenkategorie',
    'settings.defaultPriority': 'Standard-Aufgabenpriorität',
    'settings.defaults': 'Standards',
    'settings.team': 'Team',
    
    // Contacts
    'contacts.title': 'Kontakte',
    'contacts.addContact': 'Kontakt hinzufügen',
    'contacts.editContact': 'Kontakt bearbeiten',
    'contacts.deleteContact': 'Kontakt löschen',
    'contacts.noContacts': 'Keine Kontakte',
    'contacts.searchContacts': 'Kontakte suchen...',
    
    // Habits
    'habits.title': 'Gewohnheiten',
    'habits.addHabit': 'Gewohnheit hinzufügen',
    'habits.editHabit': 'Gewohnheit bearbeiten',
    'habits.deleteHabit': 'Gewohnheit löschen',
    'habits.streak': 'Serie',
    'habits.completed': 'Abgeschlossen',
    'habits.noHabits': 'Keine Gewohnheiten',
    'habits.daily': 'Täglich',
    'habits.weekly': 'Wöchentlich',
    
    // Projects
    'projects.title': 'Projekte',
    'projects.addProject': 'Projekt hinzufügen',
    'projects.editProject': 'Projekt bearbeiten',
    'projects.deleteProject': 'Projekt löschen',
    'projects.noProjects': 'Keine Projekte',
    'projects.archived': 'Archiviert',
    'projects.active': 'Aktiv',
    
    // Task Categories & Priorities
    'category.personal': 'Persönlich',
    'category.business': 'Geschäftlich',
    'category.family': 'Familie',
    'category.all': 'Alle',
    'category.shared': 'Geteilt',
    'priority.low': 'Niedrig',
    'priority.medium': 'Mittel',
    'priority.high': 'Hoch',
    
    // Task List
    'taskList.addTask': 'Aufgabe hinzufügen',
    'taskList.newTask': 'Neue Aufgabe...',
    'taskList.overdue': 'Überfällig',
    'taskList.setDueDate': 'Fälligkeitsdatum setzen',
    'taskList.clearDueDate': 'Fälligkeitsdatum löschen',
    'taskList.deleteSelected': 'Ausgewählte löschen',
    'taskList.cancel': 'Abbrechen',
    'taskList.noTasks': 'Noch keine Aufgaben',
    'taskList.startAdding': 'Beginne Aufgaben hinzuzufügen!',
    'taskList.completed': 'Erledigt',
    'taskList.editTask': 'Aufgabe bearbeiten',
    'taskList.addSubtask': 'Unteraufgabe hinzufügen',
    'taskList.sharedBy': 'Geteilt von',
    'taskList.event': 'Termin',
    'taskList.task': 'Aufgabe',
    
    // Time Filters
    'time.all': 'Alle',
    'time.today': 'Heute',
    'time.week': 'Woche',
    'time.month': 'Monat',
    'time.noDate': 'Ohne Datum',
    
    // Calendar Panel
    'calendar.agenda': 'Terminübersicht',
    'calendar.import': 'Importieren',
    'calendar.invalidFile': 'Ungültige Datei',
    'calendar.invalidFileDesc': 'Bitte laden Sie eine gültige .ics Kalenderdatei hoch.',
    'calendar.noEventsFound': 'Keine Termine gefunden',
    'calendar.noEventsFoundDesc': 'Die Datei enthält keine gültigen Termine.',
    'calendar.importSuccess': 'Import erfolgreich',
    'calendar.importedEvents': '{count} Termin(e) importiert.',
    'calendar.importFailed': 'Import fehlgeschlagen',
    'calendar.importFailedDesc': 'Kalenderdatei konnte nicht gelesen werden. Bitte Format prüfen.',
    'calendar.updatedSuccess': 'Erfolgreich aktualisiert',
    'calendar.deletedSuccess': 'Erfolgreich gelöscht',
    'calendar.noUpcoming': 'Keine anstehenden Termine oder Aufgaben',
    'calendar.tasksWithDueDates': 'Aufgaben mit Fälligkeitsdatum erscheinen hier',
    'calendar.importIcs': '.ics importieren',
    'calendar.scheduleSomething': 'Etwas planen',
    'calendar.sharedBy': 'Geteilt von',
    
    // Notes Panel
    'notes.title': 'Notizen',
    'notes.newNote': 'Neue Notiz',
    'notes.searchNotes': 'Notizen suchen...',
    'notes.noNotes': 'Noch keine Notizen',
    'notes.createFirst': 'Erstelle deine erste Notiz',
    'notes.noContent': 'Kein Inhalt',
    
    // Habits Panel
    'habits.habitsAndGoals': 'Gewohnheiten & Ziele',
    'habits.todaysProgress': 'Heutiger Fortschritt',
    'habits.addNewHabit': 'Neue Gewohnheit hinzufügen',
    'habits.noHabitsYet': 'Noch keine Gewohnheiten',
    'habits.createFirstHabit': 'Erstelle deine erste Gewohnheit',
    'habits.goals': 'Ziele',
    'habits.addNewGoal': 'Neues Ziel hinzufügen',
    'habits.noGoalsYet': 'Noch keine Ziele',
    'habits.setGoal': 'Setze ein Ziel um deinen Fortschritt zu verfolgen',
    'habits.target': 'Ziel',
    'habits.completedGoals': 'Erledigte Ziele',
    'habits.completedOn': 'Erledigt am',
    
    // Add Habit Dialog
    'addHabit.title': 'Neue Gewohnheit hinzufügen',
    'addHabit.habitName': 'Name der Gewohnheit',
    'addHabit.habitNamePlaceholder': 'z.B. 8 Gläser Wasser trinken',
    'addHabit.description': 'Beschreibung (optional)',
    'addHabit.descriptionPlaceholder': 'Warum ist diese Gewohnheit wichtig für dich?',
    'addHabit.icon': 'Symbol',
    'addHabit.color': 'Farbe',
    'addHabit.frequency': 'Häufigkeit',
    'addHabit.targetPerDay': 'Ziel pro Tag',
    'addHabit.daysOfWeek': 'Wochentage',
    'addHabit.daily': 'Täglich',
    'addHabit.weekly': 'Wöchentlich',
    'addHabit.custom': 'Benutzerdefiniert',
    'addHabit.creating': 'Erstellen...',
    'addHabit.createHabit': 'Gewohnheit erstellen',
    
    // Add Goal Dialog
    'addGoal.title': 'Neues Ziel hinzufügen',
    'addGoal.goalName': 'Zielname',
    'addGoal.goalNamePlaceholder': 'z.B. 12 Bücher dieses Jahr lesen',
    'addGoal.description': 'Beschreibung (optional)',
    'addGoal.descriptionPlaceholder': 'Was bedeutet es für dich, dieses Ziel zu erreichen?',
    'addGoal.icon': 'Symbol',
    'addGoal.color': 'Farbe',
    'addGoal.current': 'Aktuell',
    'addGoal.target': 'Ziel',
    'addGoal.unit': 'Einheit',
    'addGoal.targetDate': 'Zieldatum (optional)',
    'addGoal.pickDate': 'Datum wählen',
    'addGoal.creating': 'Erstellen...',
    'addGoal.createGoal': 'Ziel erstellen',
    
    // Edit Task Modal
    'editTask.title': 'Aufgabe bearbeiten',
    'editTask.taskTitle': 'Titel',
    'editTask.taskTitlePlaceholder': 'Aufgabentitel',
    'editTask.description': 'Beschreibung (Markdown unterstützt)',
    'editTask.descriptionPlaceholder': 'Optionale Beschreibung - unterstützt **fett**, *kursiv*, - Listen...',
    'editTask.project': 'Projekt',
    'editTask.noProject': 'Kein Projekt',
    'editTask.selectProject': 'Projekt auswählen',
    'editTask.mainResponsible': 'Hauptverantwortlich',
    'editTask.secondaryResponsible': 'Zweitverantwortlich',
    'editTask.notAssigned': 'Nicht zugewiesen',
    'editTask.priority': 'Priorität',
    'editTask.category': 'Kategorie',
    'editTask.dueDateTime': 'Fälligkeitsdatum & Uhrzeit',
    'editTask.noDueDate': 'Kein Fälligkeitsdatum',
    'editTask.clearDueDate': 'Fälligkeitsdatum löschen',
    'editTask.recurrence': 'Wiederholung',
    'editTask.noRecurrence': 'Keine Wiederholung',
    'editTask.dontRepeat': 'Nicht wiederholen',
    'editTask.customRecurrence': 'Benutzerdefinierte Wiederholung',
    'editTask.every': 'Alle',
    'editTask.onDays': 'An Tagen',
    'editTask.endDate': 'Enddatum (optional)',
    'editTask.apply': 'Anwenden',
    'editTask.reminder': 'Erinnerung',
    'editTask.noReminder': 'Keine Erinnerung',
    'editTask.checklist': 'Checkliste',
    'editTask.addItem': 'Element hinzufügen...',
    'editTask.aiBreakdown': 'KI-Aufschlüsselung',
    'editTask.saveChanges': 'Änderungen speichern',
    'editTask.deleteTask': 'Aufgabe löschen',
    
    // Reminder Options
    'reminder.none': 'Keine Erinnerung',
    'reminder.15min': '15 Minuten vorher',
    'reminder.30min': '30 Minuten vorher',
    'reminder.1hour': '1 Stunde vorher',
    'reminder.2hours': '2 Stunden vorher',
    'reminder.1day': '1 Tag vorher',
    'reminder.2days': '2 Tage vorher',
    'reminder.1week': '1 Woche vorher',
    
    // Recurrence Frequency
    'frequency.daily': 'Tag(e)',
    'frequency.weekly': 'Woche(n)',
    'frequency.monthly': 'Monat(e)',
    'frequency.yearly': 'Jahr(e)',
    
    // Weekdays
    'weekday.sun': 'So',
    'weekday.mon': 'Mo',
    'weekday.tue': 'Di',
    'weekday.wed': 'Mi',
    'weekday.thu': 'Do',
    'weekday.fri': 'Fr',
    'weekday.sat': 'Sa',
    
    // Contacts Panel
    'contacts.manageNetwork': 'Verwalte dein Netzwerk',
    'contacts.personal': 'Persönlich',
    'contacts.business': 'Geschäftlich',
    'contacts.due': 'Fällig',
    'contacts.name': 'Name',
    'contacts.email': 'E-Mail',
    'contacts.phone': 'Telefon',
    'contacts.company': 'Firma',
    'contacts.role': 'Rolle',
    'contacts.type': 'Typ',
    'contacts.tier': 'Stufe',
    'contacts.level': 'Level',
    'contacts.relationship': 'Beziehung',
    'contacts.contactFrequency': 'Kontakthäufigkeit (Tage)',
    'contacts.notes': 'Notizen',
    'contacts.tags': 'Tags (kommagetrennt)',
    'contacts.socialLinks': 'Soziale Links',
    'contacts.location': 'Standort',
    'contacts.country': 'Land',
    'contacts.city': 'Stadt',
    'contacts.save': 'Speichern',
    'contacts.confirmDelete': 'Löschen bestätigen',
    'contacts.confirmDeleteDesc': 'Bist du sicher, dass du diesen Kontakt löschen möchtest? Diese Aktion kann nicht rückgängig gemacht werden.',
    'contacts.contactUpdated': 'Kontakt aktualisiert',
    'contacts.contactAdded': 'Kontakt hinzugefügt',
    'contacts.contactDeleted': 'Kontakt gelöscht',
    'contacts.markedContacted': 'Als kontaktiert markiert',
    'contacts.selectTier': 'Stufe auswählen',
    'contacts.selectLevel': 'Level auswählen',
    'contacts.selectRelationship': 'Beziehung auswählen',
    
    // Personal Tiers
    'tier.family': 'Familie',
    'tier.closeFriend': 'Enger Freund',
    'tier.friend': 'Freund',
    'tier.acquaintance': 'Bekannter',
    
    // Business Levels
    'level.veryWell': 'Kenne sehr gut',
    'level.well': 'Kenne gut',
    'level.barely': 'Kenne kaum',
    'level.notContacted': 'Noch nicht kontaktiert',
    
    // Contracts Panel
    'contracts.title': 'Verträge & Abonnements',
    'contracts.subtitle': 'Verwalte deine Verträge, Abonnements und wiederkehrenden Zahlungen',
    'contracts.addContract': 'Vertrag hinzufügen',
    'contracts.editContract': 'Vertrag bearbeiten',
    'contracts.deleteContract': 'Vertrag löschen',
    'contracts.monthlyCost': 'Monatliche Kosten',
    'contracts.yearlyCost': 'Jährliche Kosten',
    'contracts.activeContracts': 'Aktive Verträge',
    'contracts.expiringSoon': 'Läuft bald ab',
    'contracts.searchContracts': 'Verträge suchen...',
    'contracts.noContractsSearch': 'Keine Verträge entsprechen deiner Suche',
    'contracts.noContracts': 'Noch keine Verträge. Füge deinen ersten Vertrag hinzu!',
    'contracts.cancellationDeadlines': 'Anstehende Kündigungsfristen',
    'contracts.cancelBy': 'Kündigen bis',
    'contracts.contract': 'Vertrag',
    'contracts.provider': 'Anbieter',
    'contracts.category': 'Kategorie',
    'contracts.cost': 'Kosten',
    'contracts.renewal': 'Verlängerung',
    'contracts.status': 'Status',
    'contracts.actions': 'Aktionen',
    'contracts.active': 'Aktiv',
    'contracts.inactive': 'Inaktiv',
    'contracts.auto': 'Auto',
    'contracts.all': 'Alle',
    'contracts.confirmDeleteTitle': 'Vertrag löschen?',
    'contracts.confirmDeleteDesc': 'Bist du sicher, dass du diesen Vertrag löschen möchtest? Diese Aktion kann nicht rückgängig gemacht werden.',
    
    // Family Panel
    'family.title': 'Familien-Hub',
    'family.subtitle': 'Verwalte deine Familie, Haushaltsaufgaben und Termine',
    'family.members': 'Mitglieder',
    'family.kids': 'Kinder',
    'family.tasks': 'Aufgaben',
    'family.meals': 'Mahlzeiten',
    'family.shopping': 'Einkauf',
    'family.budget': 'Budget',
    'family.health': 'Gesundheit',
    'family.docs': 'Dokumente',
    'family.calendar': 'Kalender',
    
    // Cooking Panel
    'cooking.title': 'Kochen & Essen',
    'cooking.subtitle': 'Plane deine Mahlzeiten und verwalte Rezepte',
    'nav.cooking': 'Kochen',
    
    // Mobile Navigation
    'nav.dori': 'Dori',
    'nav.allTasks': 'Alle Aufgaben',
    'nav.business': 'Geschäftlich',
    'nav.personal': 'Persönlich',
    'nav.sharedWithMe': 'Mit mir geteilt',
    'nav.familyHub': 'Familien-Hub',
    
    // Islam Panel
    'islam.title': 'Islam',
    'islam.prayer': 'Gebet',
    'islam.qibla': 'Qibla',
    'islam.quran': 'Quran',
    'islam.hifz': 'Hifz',
    'islam.hadith': 'Hadith',
    'islam.duas': 'Duas',
    'islam.calendar': 'Kalender',
    'islam.qiblaFinder': 'Qibla-Finder',
    'islam.findQibla': 'Qibla finden',
    'islam.loading': 'Laden...',
    'islam.yourLocation': 'Dein Standort',
    'islam.qiblaDirection': 'Qibla-Richtung',
    'islam.locationNeeded': 'Standortzugriff erforderlich',
    'islam.enableLocation': 'Standort aktivieren',
    'islam.searchSurah': 'Sure suchen...',
    'islam.verses': 'Verse',
    'islam.selectSurah': 'Wähle eine Sure zum Lesen',
    'islam.readQuran': 'Den Heiligen Quran lesen',
    'islam.duaCollection': 'Dua-Sammlung',
    'islam.allCategories': 'Alle Kategorien',
    'islam.islamicCalendar': 'Islamischer Kalender',
    'islam.hijriDate': 'Hijri-Datum',
    'islam.today': 'Heute',
    
    // Auth
    'auth.displayName': 'Anzeigename',
    'auth.yourName': 'Dein Name',
    'auth.email': 'E-Mail',
    'auth.password': 'Passwort',
    'auth.signIn': 'Anmelden',
    'auth.createAccount': 'Konto erstellen',
    'auth.dontHaveAccount': 'Noch kein Konto? Registrieren',
    'auth.alreadyHaveAccount': 'Bereits ein Konto? Anmelden',
    'auth.loginFailed': 'Anmeldung fehlgeschlagen',
    'auth.welcomeBack': 'Willkommen zurück!',
    'auth.successLogin': 'Erfolgreich angemeldet.',
    'auth.accountExists': 'Konto existiert',
    'auth.emailAlreadyRegistered': 'Diese E-Mail ist bereits registriert. Bitte anmelden.',
    'auth.signUpFailed': 'Registrierung fehlgeschlagen',
    'auth.accountCreated': 'Konto erstellt!',
    'auth.startUsingApp': 'Du kannst jetzt DarAI nutzen.',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('app-language');
    return (saved as Language) || 'de';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('app-language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
