/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live */
        get: operations["live_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Metrics */
        get: operations["metrics_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/actions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Action */
        post: operations["create_action_v1_actions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/actions/{action_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve Action */
        post: operations["approve_action_v1_actions__action_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/security/inspect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Inspect Untrusted Content */
        post: operations["inspect_untrusted_content_v1_security_inspect_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/telegram/bindings/{binding_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Telegram Binding Status */
        get: operations["telegram_binding_status_v1_telegram_bindings__binding_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/telegram/bindings/{binding_id}/test-message": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Telegram Test Message */
        post: operations["telegram_test_message_v1_telegram_bindings__binding_id__test_message_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/telegram/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Telegram Setup */
        post: operations["telegram_setup_v1_telegram_setup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/telegram/webhook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Telegram Webhook */
        post: operations["telegram_webhook_v1_telegram_webhook_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/today": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Today */
        get: operations["today_v1_today_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActionApprovalRequest */
        ActionApprovalRequest: {
            /**
             * Actor
             * @default user_demo
             */
            actor: string;
            /** @default web */
            channel: components["schemas"]["ApprovalChannel"];
            /**
             * Fresh Auth
             * @default false
             */
            fresh_auth: boolean;
        };
        /** ActionCreateRequest */
        ActionCreateRequest: {
            /**
             * Action Type
             * @default create_email_draft
             */
            action_type: string;
            /** Changed Fields */
            changed_fields?: string[];
            /**
             * External Side Effect
             * @default true
             */
            external_side_effect: boolean;
            /** Idempotency Key */
            idempotency_key?: string | null;
            /** Recipient Refs */
            recipient_refs?: string[];
            /**
             * Reversible
             * @default true
             */
            reversible: boolean;
            /** @default medium */
            risk_tier: components["schemas"]["RiskTier"];
            scope?: components["schemas"]["ScopedIdentity"];
            /**
             * Sending Account Ref
             * @default onebrain://connected-account/demo-mail
             */
            sending_account_ref: string | null;
            /** Sensitive Flags */
            sensitive_flags?: string[];
            /** Source Refs */
            source_refs?: string[];
            /**
             * Summary
             * @default Draft a reply for review.
             */
            summary: string;
        };
        /** ActionRecord */
        ActionRecord: {
            /**
             * Action Id
             * Format: uuid
             */
            action_id?: string;
            /** Action Type */
            action_type: string;
            /**
             * Approval Reason
             * @default User approval required by action policy.
             */
            approval_reason: string;
            /** Audit Correlation Id */
            audit_correlation_id?: string;
            /** Changed Fields */
            changed_fields?: string[];
            /** Correlation Id */
            correlation_id?: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /**
             * External Side Effect
             * @default true
             */
            external_side_effect: boolean;
            /** Idempotency Key */
            idempotency_key: string;
            /** Recipient Refs */
            recipient_refs?: string[];
            /**
             * Reversible
             * @default false
             */
            reversible: boolean;
            risk_tier: components["schemas"]["RiskTier"];
            scope: components["schemas"]["ScopedIdentity"];
            /** Sending Account Ref */
            sending_account_ref?: string | null;
            /** Sensitive Flags */
            sensitive_flags?: string[];
            /** Source Refs */
            source_refs?: string[];
            /** @default proposed */
            state: components["schemas"]["ActionState"];
            /** Summary */
            summary: string;
            /** Transitions */
            transitions?: components["schemas"]["TransitionRecord"][];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at?: string;
        };
        /**
         * ActionState
         * @enum {string}
         */
        ActionState: "proposed" | "needs_review" | "approved" | "executing" | "executed" | "failed" | "cancelled";
        /** ApprovalCard */
        ApprovalCard: {
            /** Action Id */
            action_id: string;
            /** Action Type */
            action_type: string;
            /** Approval Reason */
            approval_reason: string;
            /** Changed Fields */
            changed_fields: string[];
            /** Primary Channel */
            primary_channel: string;
            /** Recipient Refs */
            recipient_refs: string[];
            /** Reversible */
            reversible: boolean;
            risk_tier: components["schemas"]["RiskTier"];
            /** Sending Account */
            sending_account: string;
            /** Sensitive Flags */
            sensitive_flags: string[];
            /** Source Ref */
            source_ref: string;
            /** Summary */
            summary: string;
        };
        /**
         * ApprovalChannel
         * @enum {string}
         */
        ApprovalChannel: "web" | "telegram" | "voice" | "worker" | "fresh_auth";
        /** DegradedModeState */
        DegradedModeState: {
            /** Active */
            active: boolean;
            /** Allowed Actions */
            allowed_actions?: string[];
            /** Blocked Actions */
            blocked_actions?: string[];
            /** Reason */
            reason?: string | null;
        };
        /** FirewallDecision */
        FirewallDecision: {
            /** Blocked Reasons */
            blocked_reasons?: string[];
            /**
             * Can Create Action From Raw Content
             * @default false
             */
            can_create_action_from_raw_content: boolean;
            /** Extracted Intent */
            extracted_intent?: string | null;
            /** Proposed Recipient Refs */
            proposed_recipient_refs?: string[];
            /** Risk Flags */
            risk_flags?: string[];
            /** Safe For Model Context */
            safe_for_model_context: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Checks */
            checks: {
                [key: string]: string;
            };
            /** Correlation Id */
            correlation_id: string;
            /** Degraded */
            degraded: boolean;
            /** Service */
            service: string;
            /** Status */
            status: string;
            /** Version */
            version: string;
        };
        /** NavigationItem */
        NavigationItem: {
            /** Count */
            count?: number | null;
            /** Href */
            href: string;
            /** Key */
            key: string;
            /** Label */
            label: string;
        };
        /** ProviderHealth */
        ProviderHealth: {
            /**
             * Checked At
             * Format: date-time
             */
            checked_at?: string;
            /** Detail */
            detail: string;
            /** Provider */
            provider: string;
            /** Status */
            status: string;
        };
        /**
         * RiskTier
         * @enum {string}
         */
        RiskTier: "low" | "medium" | "high";
        /** SanitizedContent */
        SanitizedContent: {
            /** Removed Markers */
            removed_markers?: string[];
            /** Risk Flags */
            risk_flags?: string[];
            /** Safe Text */
            safe_text: string;
        };
        /** ScopedIdentity */
        ScopedIdentity: {
            /** Account Id */
            account_id: string;
            /**
             * Purpose
             * @default assistant_operations
             */
            purpose: string;
            /** Space Id */
            space_id: string;
            /** User Id */
            user_id: string;
        };
        /** SecurityInspectionRequest */
        SecurityInspectionRequest: {
            /** Html */
            html: string;
            /**
             * Source Ref
             * @default onebrain://fixture/untrusted
             */
            source_ref: string;
        };
        /** SecurityInspectionResponse */
        SecurityInspectionResponse: {
            firewall: components["schemas"]["FirewallDecision"];
            sanitized: components["schemas"]["SanitizedContent"];
        };
        /**
         * TelegramBindingStatus
         * @enum {string}
         */
        TelegramBindingStatus: "pending" | "verified" | "paused" | "revoked" | "expired";
        /** TelegramBindingStatusResponse */
        TelegramBindingStatusResponse: {
            /** Account Id */
            account_id: string;
            /** Audit Correlation Id */
            audit_correlation_id: string;
            /**
             * Binding Id
             * Format: uuid
             */
            binding_id: string;
            /** Correlation Id */
            correlation_id: string;
            /**
             * Paused
             * @default false
             */
            paused: boolean;
            /** Space Id */
            space_id: string;
            status: components["schemas"]["TelegramBindingStatus"];
            /** User Id */
            user_id: string;
            /** Verified At */
            verified_at?: string | null;
        };
        /** TelegramSetupRequest */
        TelegramSetupRequest: {
            /** Bot Token */
            bot_token: string;
            /**
             * Expires In Seconds
             * @default 600
             */
            expires_in_seconds: number;
            scope?: components["schemas"]["ScopedIdentity"];
        };
        /** TelegramSetupResponse */
        TelegramSetupResponse: {
            /** Audit Correlation Id */
            audit_correlation_id: string;
            /** Binding Code */
            binding_code: string;
            /** Binding Command */
            binding_command: string;
            /**
             * Binding Id
             * Format: uuid
             */
            binding_id: string;
            /** Bot Secret Ref */
            bot_secret_ref: string;
            /** Correlation Id */
            correlation_id: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            status: components["schemas"]["TelegramBindingStatus"];
            /** Token Preview */
            token_preview: string;
        };
        /** TelegramTestMessageRequest */
        TelegramTestMessageRequest: {
            /** Idempotency Key */
            idempotency_key?: string | null;
            /**
             * Message
             * @default Telegram is connected to your OneBrain assistant.
             */
            message: string;
        };
        /** TelegramTestMessageResponse */
        TelegramTestMessageResponse: {
            /** Audit Correlation Id */
            audit_correlation_id: string;
            /**
             * Binding Id
             * Format: uuid
             */
            binding_id: string;
            /** Correlation Id */
            correlation_id: string;
            /** Delivery Ref */
            delivery_ref: string;
            /** Detail */
            detail: string;
            /** Event Ref */
            event_ref: string;
            /**
             * Outbox Id
             * Format: uuid
             */
            outbox_id: string;
            /** Status */
            status: string;
        };
        /** TelegramWebhookResponse */
        TelegramWebhookResponse: {
            /** Binding Id */
            binding_id?: string | null;
            /** Command */
            command?: string | null;
            /** Correlation Id */
            correlation_id?: string;
            /** Detail */
            detail: string;
            /** Event Ref */
            event_ref?: string | null;
            /** Status */
            status: string;
        };
        /** TodayBriefItem */
        TodayBriefItem: {
            /** Detail */
            detail: string;
            /** Source Ref */
            source_ref: string;
            /**
             * Status
             * @default ready
             */
            status: string;
            /** Title */
            title: string;
        };
        /** TodayResponse */
        TodayResponse: {
            /** Account Id */
            account_id: string;
            /** Approvals */
            approvals: components["schemas"]["ApprovalCard"][];
            /** Brief */
            brief: components["schemas"]["TodayBriefItem"][];
            degraded_mode: components["schemas"]["DegradedModeState"];
            /** Local Date */
            local_date: string;
            /** Navigation */
            navigation: components["schemas"]["NavigationItem"][];
            /** Provider Health */
            provider_health: components["schemas"]["ProviderHealth"][];
            /** Space Id */
            space_id: string;
            /** User Id */
            user_id: string;
        };
        /** TransitionRecord */
        TransitionRecord: {
            /** Actor */
            actor: string;
            channel?: components["schemas"]["ApprovalChannel"] | null;
            /** Correlation Id */
            correlation_id: string;
            from_state: components["schemas"]["ActionState"] | null;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at?: string;
            /** Reason */
            reason: string;
            to_state: components["schemas"]["ActionState"];
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    live_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    ready_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    metrics_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    create_action_v1_actions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActionCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_action_v1_actions__action_id__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                action_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActionApprovalRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    inspect_untrusted_content_v1_security_inspect_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SecurityInspectionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SecurityInspectionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    telegram_binding_status_v1_telegram_bindings__binding_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                binding_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TelegramBindingStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    telegram_test_message_v1_telegram_bindings__binding_id__test_message_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                binding_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TelegramTestMessageRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TelegramTestMessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    telegram_setup_v1_telegram_setup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TelegramSetupRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TelegramSetupResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    telegram_webhook_v1_telegram_webhook_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Telegram-Bot-Api-Secret-Token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TelegramWebhookResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    today_v1_today_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TodayResponse"];
                };
            };
        };
    };
}
