/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live */
        get: operations["live_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Metrics */
        get: operations["metrics_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/actions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Action */
        post: operations["create_action_v1_actions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/actions/{action_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve Action */
        post: operations["approve_action_v1_actions__action_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/actions/{action_id}/draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Edit Draft */
        post: operations["edit_draft_v1_actions__action_id__draft_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/assistant/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Assistant Ask */
        post: operations["assistant_ask_v1_assistant_ask_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Session Info */
        get: operations["session_info_v1_auth_session_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/brain/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Brain Audit Event */
        post: operations["create_brain_audit_event_v1_brain_audit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/brain/records": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Brain Records */
        get: operations["list_brain_records_v1_brain_records_get"];
        put?: never;
        /** Create Brain Record */
        post: operations["create_brain_record_v1_brain_records_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/brain/records/{record_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Brain Record */
        get: operations["get_brain_record_v1_brain_records__record_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/drafts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Propose Draft */
        post: operations["propose_draft_v1_drafts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Provider Status */
        get: operations["provider_status_v1_providers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/providers/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Provider Accounts */
        get: operations["provider_accounts_v1_providers_accounts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/providers/accounts/{account_id}/disconnect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Provider Disconnect */
        post: operations["provider_disconnect_v1_providers_accounts__account_id__disconnect_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/providers/accounts/{account_id}/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Provider Account Health */
        get: operations["provider_account_health_v1_providers_accounts__account_id__health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/providers/accounts/{account_id}/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Provider Sync */
        post: operations["provider_sync_v1_providers_accounts__account_id__sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/providers/oauth/{provider}/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Provider Oauth Callback */
        get: operations["provider_oauth_callback_v1_providers_oauth__provider__callback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/providers/oauth/{provider}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Provider Oauth Start */
        post: operations["provider_oauth_start_v1_providers_oauth__provider__start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/providers/webhooks/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Google Provider Webhook */
        post: operations["google_provider_webhook_v1_providers_webhooks_google_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/providers/webhooks/microsoft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Microsoft Provider Webhook */
        post: operations["microsoft_provider_webhook_v1_providers_webhooks_microsoft_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/security/inspect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Inspect Untrusted Content */
        post: operations["inspect_untrusted_content_v1_security_inspect_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/telegram/bindings/{binding_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Telegram Binding Status */
        get: operations["telegram_binding_status_v1_telegram_bindings__binding_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/telegram/bindings/{binding_id}/test-message": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Telegram Test Message */
        post: operations["telegram_test_message_v1_telegram_bindings__binding_id__test_message_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/telegram/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Telegram Setup */
        post: operations["telegram_setup_v1_telegram_setup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/telegram/webhook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Telegram Webhook */
        post: operations["telegram_webhook_v1_telegram_webhook_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/today": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Today */
        get: operations["today_v1_today_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workday/brief": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Workday Brief */
        get: operations["workday_brief_v1_workday_brief_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workday/brief/schedule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Schedule Morning Brief */
        post: operations["schedule_morning_brief_v1_workday_brief_schedule_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workday/calendar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Workday Calendar */
        get: operations["workday_calendar_v1_workday_calendar_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workday/follow-ups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Workday Follow Ups */
        get: operations["workday_follow_ups_v1_workday_follow_ups_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workday/inbox": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Workday Inbox */
        get: operations["workday_inbox_v1_workday_inbox_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workday/regenerate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Workday Regenerate */
        post: operations["workday_regenerate_v1_workday_regenerate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workday/today": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Workday Today */
        get: operations["workday_today_v1_workday_today_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActionApprovalRequest */
        ActionApprovalRequest: {
            /**
             * Actor
             * @default user_demo
             */
            actor: string;
            /** @default web */
            channel: components["schemas"]["ApprovalChannel"];
            /** Content Hash */
            content_hash?: string | null;
            /**
             * Fresh Auth
             * @default false
             */
            fresh_auth: boolean;
        };
        /** ActionCreateRequest */
        ActionCreateRequest: {
            /**
             * Action Type
             * @default create_email_draft
             */
            action_type: string;
            /** Changed Fields */
            changed_fields?: string[];
            /**
             * Draft Body
             * @default
             */
            draft_body: string;
            /**
             * Draft Subject
             * @default
             */
            draft_subject: string;
            /**
             * External Side Effect
             * @default true
             */
            external_side_effect: boolean;
            /** Idempotency Key */
            idempotency_key?: string | null;
            /** Recipient Refs */
            recipient_refs?: string[];
            /**
             * Reversible
             * @default true
             */
            reversible: boolean;
            /** @default medium */
            risk_tier: components["schemas"]["RiskTier"];
            scope?: components["schemas"]["ScopedIdentity"];
            /**
             * Sending Account Ref
             * @default onebrain://connected-account/demo-mail
             */
            sending_account_ref: string | null;
            /** Sensitive Flags */
            sensitive_flags?: string[];
            /** Source Refs */
            source_refs?: string[];
            /**
             * Summary
             * @default Draft a reply for review.
             */
            summary: string;
        };
        /** ActionRecord */
        ActionRecord: {
            /**
             * Action Id
             * Format: uuid
             */
            action_id?: string;
            /** Action Type */
            action_type: string;
            /**
             * Approval Reason
             * @default User approval required by action policy.
             */
            approval_reason: string;
            /** Audit Correlation Id */
            audit_correlation_id?: string;
            /** Changed Fields */
            changed_fields?: string[];
            /**
             * Content Hash
             * @default
             */
            content_hash: string;
            /** Correlation Id */
            correlation_id?: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /**
             * Draft Body
             * @default
             */
            draft_body: string;
            /**
             * Draft Subject
             * @default
             */
            draft_subject: string;
            /**
             * External Side Effect
             * @default true
             */
            external_side_effect: boolean;
            /** Idempotency Key */
            idempotency_key: string;
            /** Recipient Refs */
            recipient_refs?: string[];
            /**
             * Reversible
             * @default false
             */
            reversible: boolean;
            risk_tier: components["schemas"]["RiskTier"];
            scope: components["schemas"]["ScopedIdentity"];
            /** Sending Account Ref */
            sending_account_ref?: string | null;
            /** Sensitive Flags */
            sensitive_flags?: string[];
            /** Source Refs */
            source_refs?: string[];
            /** @default proposed */
            state: components["schemas"]["ActionState"];
            /** Summary */
            summary: string;
            /** Transitions */
            transitions?: components["schemas"]["TransitionRecord"][];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at?: string;
        };
        /**
         * ActionState
         * @enum {string}
         */
        ActionState: "proposed" | "needs_review" | "approved" | "executing" | "executed" | "failed" | "cancelled";
        /** ApprovalCard */
        ApprovalCard: {
            /** Action Id */
            action_id: string;
            /** Action Type */
            action_type: string;
            /** Approval Reason */
            approval_reason: string;
            /** Changed Fields */
            changed_fields: string[];
            /**
             * Content Hash
             * @default
             */
            content_hash: string;
            /**
             * Draft Body
             * @default
             */
            draft_body: string;
            /**
             * Draft Subject
             * @default
             */
            draft_subject: string;
            /** Primary Channel */
            primary_channel: string;
            /** Recipient Refs */
            recipient_refs: string[];
            /** Reversible */
            reversible: boolean;
            risk_tier: components["schemas"]["RiskTier"];
            /** Sending Account */
            sending_account: string;
            /** Sensitive Flags */
            sensitive_flags: string[];
            /** Source Ref */
            source_ref: string;
            /** Summary */
            summary: string;
        };
        /**
         * ApprovalChannel
         * @enum {string}
         */
        ApprovalChannel: "web" | "telegram" | "voice" | "worker" | "fresh_auth";
        /** AssistantAskRequest */
        AssistantAskRequest: {
            /** Local Date */
            local_date?: string | null;
            /** Question */
            question: string;
        };
        /** AssistantAskResponse */
        AssistantAskResponse: {
            /** Answer */
            answer: string;
            /** Intent */
            intent: string;
            /** Sources */
            sources?: string[];
            /** Spoken */
            spoken: string;
        };
        /** BrainAuditEventRequest */
        BrainAuditEventRequest: {
            /** Action */
            action: string;
            /**
             * Decision
             * @default recorded
             */
            decision: string;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
            /**
             * Purpose
             * @default assistant_action
             */
            purpose: string;
            scope?: components["schemas"]["ScopedIdentity"];
            /** Target Id */
            target_id: string;
            /** Target Type */
            target_type: string;
        };
        /** BrainAuditEventResponse */
        BrainAuditEventResponse: {
            /** Event */
            event: {
                [key: string]: unknown;
            };
        };
        /** BrainRecordCreateRequest */
        BrainRecordCreateRequest: {
            /** Content */
            content: string;
            /**
             * Intent
             * @default
             */
            intent: string;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
            /** Provenance */
            provenance?: {
                [key: string]: unknown;
            };
            /**
             * Purpose
             * @default assistant_context
             */
            purpose: string;
            /** Record Type */
            record_type: string;
            /** Retention */
            retention?: {
                [key: string]: unknown;
            };
            scope?: components["schemas"]["ScopedIdentity"];
            /**
             * Source
             * @default assistant
             */
            source: string;
            /**
             * Source Ref
             * @default
             */
            source_ref: string;
            /**
             * Title
             * @default
             */
            title: string;
        };
        /** BrainRecordListResponse */
        BrainRecordListResponse: {
            /** Records */
            records?: {
                [key: string]: unknown;
            }[];
        };
        /** BrainRecordResponse */
        BrainRecordResponse: {
            /** Record */
            record: {
                [key: string]: unknown;
            };
        };
        /** CalendarFocusWindow */
        CalendarFocusWindow: {
            /**
             * End At
             * Format: date-time
             */
            end_at: string;
            /** Quality */
            quality: string;
            /** Reason */
            reason: string;
            /**
             * Start At
             * Format: date-time
             */
            start_at: string;
            /** Window Id */
            window_id: string;
        };
        /** CalendarInsight */
        CalendarInsight: {
            /**
             * Confidence
             * @default 0.7
             */
            confidence: number;
            /** Detail */
            detail: string;
            /** Focus Windows */
            focus_windows?: components["schemas"]["CalendarFocusWindow"][];
            /** Insight Id */
            insight_id: string;
            /** Move Candidates */
            move_candidates?: string[];
            /**
             * Severity
             * @default info
             */
            severity: string;
            /** Source Refs */
            source_refs?: string[];
            /** Title */
            title: string;
        };
        /** DegradedModeState */
        DegradedModeState: {
            /** Active */
            active: boolean;
            /** Allowed Actions */
            allowed_actions?: string[];
            /** Blocked Actions */
            blocked_actions?: string[];
            /** Reason */
            reason?: string | null;
        };
        /** DraftProposalRequest */
        DraftProposalRequest: {
            /** Recipient Ref */
            recipient_ref: string;
            /** @default medium */
            risk_tier: components["schemas"]["RiskTier"];
            /** Sending Account Ref */
            sending_account_ref?: string | null;
            /** Source Ref */
            source_ref: string;
            /**
             * Subject
             * @default
             */
            subject: string;
        };
        /** DraftUpdateRequest */
        DraftUpdateRequest: {
            /**
             * Body
             * @default
             */
            body: string;
            /** Recipient Refs */
            recipient_refs?: string[];
            /**
             * Subject
             * @default
             */
            subject: string;
        };
        /** FirewallDecision */
        FirewallDecision: {
            /** Blocked Reasons */
            blocked_reasons?: string[];
            /**
             * Can Create Action From Raw Content
             * @default false
             */
            can_create_action_from_raw_content: boolean;
            /** Extracted Intent */
            extracted_intent?: string | null;
            /** Proposed Recipient Refs */
            proposed_recipient_refs?: string[];
            /** Risk Flags */
            risk_flags?: string[];
            /** Safe For Model Context */
            safe_for_model_context: boolean;
        };
        /** FollowUpRisk */
        FollowUpRisk: {
            /**
             * Confidence
             * @default 0.7
             */
            confidence: number;
            /** Detail */
            detail: string;
            /** Due At */
            due_at?: string | null;
            /** Owner */
            owner: string;
            /** Reason */
            reason: string;
            /** Risk Id */
            risk_id: string;
            /** Source Refs */
            source_refs?: string[];
            /**
             * Status
             * @default watch
             */
            status: string;
            /** Title */
            title: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Checks */
            checks: {
                [key: string]: string;
            };
            /** Correlation Id */
            correlation_id: string;
            /** Degraded */
            degraded: boolean;
            /** Service */
            service: string;
            /** Status */
            status: string;
            /** Version */
            version: string;
        };
        /** InboxTriageItem */
        InboxTriageItem: {
            /**
             * Account Ref
             * @default
             */
            account_ref: string;
            /** Category */
            category: string;
            /**
             * Confidence
             * @default 0.7
             */
            confidence: number;
            /** Flags */
            flags?: string[];
            /** Item Id */
            item_id: string;
            /**
             * Priority Score
             * @default 50
             */
            priority_score: number;
            /** Reason */
            reason: string;
            /**
             * Received At
             * Format: date-time
             */
            received_at?: string;
            /** Sender */
            sender: string;
            /** Source Ref */
            source_ref: string;
            /** Subject */
            subject: string;
        };
        /** JobRecord */
        JobRecord: {
            /** Audit Correlation Id */
            audit_correlation_id?: string;
            /** Correlation Id */
            correlation_id?: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /** Idempotency Key */
            idempotency_key: string;
            /**
             * Job Id
             * Format: uuid
             */
            job_id?: string;
            /** Job Type */
            job_type: string;
            /** Last Error */
            last_error?: string | null;
            /** Lease Expires At */
            lease_expires_at?: string | null;
            /** Lease Owner */
            lease_owner?: string | null;
            /** Payload Ref */
            payload_ref: string;
            /**
             * Retry Count
             * @default 0
             */
            retry_count: number;
            /**
             * Run At
             * Format: date-time
             */
            run_at: string;
            scope: components["schemas"]["ScopedIdentity"];
            /** @default queued */
            state: components["schemas"]["JobState"];
            /** Timezone */
            timezone: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at?: string;
        };
        /**
         * JobState
         * @enum {string}
         */
        JobState: "queued" | "leased" | "running" | "succeeded" | "retry_wait" | "failed" | "dead_lettered" | "cancelled";
        /** LoginRequest */
        LoginRequest: {
            /** Account Id */
            account_id?: string | null;
            /** Email */
            email?: string | null;
            /** Password */
            password?: string | null;
            /** Space Id */
            space_id?: string | null;
            /** User Id */
            user_id?: string | null;
        };
        /** LoginResponse */
        LoginResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Identity Source */
            identity_source: string;
            scope: components["schemas"]["ScopedIdentity"];
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** LogoutResponse */
        LogoutResponse: {
            /**
             * Detail
             * @default Session revoked.
             */
            detail: string;
            /**
             * Status
             * @default revoked
             */
            status: string;
        };
        /** MorningBriefScheduleRequest */
        MorningBriefScheduleRequest: {
            /**
             * Local Time
             * @default 07:30
             */
            local_time: string;
            /**
             * Timezone
             * @default UTC
             */
            timezone: string;
        };
        /** MorningBriefScheduleResponse */
        MorningBriefScheduleResponse: {
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            /** Local Time */
            local_time: string;
            /**
             * Run At
             * Format: date-time
             */
            run_at: string;
            /** Status */
            status: string;
            /** Timezone */
            timezone: string;
        };
        /** NavigationItem */
        NavigationItem: {
            /** Count */
            count?: number | null;
            /** Href */
            href: string;
            /** Key */
            key: string;
            /** Label */
            label: string;
        };
        /**
         * OAuthConnectionStatus
         * @enum {string}
         */
        OAuthConnectionStatus: "pending" | "completed" | "cancelled" | "failed" | "expired";
        /**
         * OAuthScopeTier
         * @enum {string}
         */
        OAuthScopeTier: "read_only" | "draft_write" | "send" | "calendar_write";
        /** PriorityItem */
        PriorityItem: {
            /**
             * Confidence
             * @default 0.75
             */
            confidence: number;
            /** Detail */
            detail: string;
            /** Priority Id */
            priority_id: string;
            /** Reason */
            reason: string;
            /** Score */
            score: number;
            /** Source Refs */
            source_refs?: string[];
            /**
             * Status
             * @default ready
             */
            status: string;
            /** Title */
            title: string;
        };
        /** ProviderAccountHealthResponse */
        ProviderAccountHealthResponse: {
            /** Detail */
            detail: string;
            /** Last Status Detail */
            last_status_detail?: string | null;
            /** Last Sync At */
            last_sync_at?: string | null;
            /** Last Sync Error */
            last_sync_error?: string | null;
            last_sync_error_class?: components["schemas"]["ProviderFailureClass"] | null;
            /** @default healthy */
            last_sync_status: components["schemas"]["ProviderOperationalSyncStatus"];
            provider: components["schemas"]["ProviderKind"];
            /**
             * Provider Account Id
             * Format: uuid
             */
            provider_account_id: string;
            /** Retry After */
            retry_after?: string | null;
            /** Stale Since */
            stale_since?: string | null;
            status: components["schemas"]["ProviderAccountStatus"];
            sync_state: components["schemas"]["ProviderSyncState"];
        };
        /**
         * ProviderAccountStatus
         * @enum {string}
         */
        ProviderAccountStatus: "not_configured" | "connecting" | "connected" | "degraded" | "disconnected" | "revoked";
        /** ProviderAccountSummary */
        ProviderAccountSummary: {
            /** Calendar Enabled */
            calendar_enabled: boolean;
            /** Capabilities */
            capabilities: components["schemas"]["ProviderCapabilityStatus"][];
            /**
             * Checked At
             * Format: date-time
             */
            checked_at?: string;
            /** Display Name */
            display_name: string;
            /** Email */
            email: string;
            /** Granted Scopes */
            granted_scopes: string[];
            /** Last Status Detail */
            last_status_detail?: string | null;
            /** Last Sync At */
            last_sync_at?: string | null;
            /** Last Sync Error */
            last_sync_error?: string | null;
            last_sync_error_class?: components["schemas"]["ProviderFailureClass"] | null;
            /** @default healthy */
            last_sync_status: components["schemas"]["ProviderOperationalSyncStatus"];
            /** Mail Enabled */
            mail_enabled: boolean;
            /** Missing Scopes */
            missing_scopes: string[];
            provider: components["schemas"]["ProviderKind"];
            /**
             * Provider Account Id
             * Format: uuid
             */
            provider_account_id: string;
            /** Provider Account Ref */
            provider_account_ref: string;
            /** Retry After */
            retry_after?: string | null;
            scope_tier: components["schemas"]["OAuthScopeTier"];
            /** Stale Since */
            stale_since?: string | null;
            status: components["schemas"]["ProviderAccountStatus"];
            sync_state: components["schemas"]["ProviderSyncState"];
        };
        /** ProviderAccountsResponse */
        ProviderAccountsResponse: {
            /** Accounts */
            accounts?: components["schemas"]["ProviderAccountSummary"][];
        };
        /** ProviderCapabilityStatus */
        ProviderCapabilityStatus: {
            /** Granted */
            granted: boolean;
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Required Scopes */
            required_scopes?: string[];
            service: components["schemas"]["ProviderService"];
            /** @default read_only */
            upgrade_tier: components["schemas"]["OAuthScopeTier"];
        };
        /** ProviderConfigurationStatus */
        ProviderConfigurationStatus: {
            /** Configured */
            configured: boolean;
            /** Display Name */
            display_name: string;
            /** Missing Config */
            missing_config?: string[];
            provider: components["schemas"]["ProviderKind"];
            /** Read Scopes */
            read_scopes?: string[];
            /** Upgrade Scopes */
            upgrade_scopes?: {
                [key: string]: string[];
            };
        };
        /** ProviderDisconnectResponse */
        ProviderDisconnectResponse: {
            /** Detail */
            detail: string;
            status: components["schemas"]["ProviderAccountStatus"];
        };
        /**
         * ProviderFailureClass
         * @enum {string}
         */
        ProviderFailureClass: "throttled" | "transient" | "provider_unavailable" | "auth" | "cursor_expired" | "permanent";
        /** ProviderHealth */
        ProviderHealth: {
            /**
             * Checked At
             * Format: date-time
             */
            checked_at?: string;
            /** Detail */
            detail: string;
            /** Provider */
            provider: string;
            /** Status */
            status: string;
        };
        /**
         * ProviderKind
         * @enum {string}
         */
        ProviderKind: "google" | "microsoft";
        /** ProviderOAuthCallbackResponse */
        ProviderOAuthCallbackResponse: {
            /** Detail */
            detail: string;
            provider: components["schemas"]["ProviderKind"];
            /** Provider Account Id */
            provider_account_id?: string | null;
            /** Redirect To */
            redirect_to: string;
            status: components["schemas"]["OAuthConnectionStatus"];
        };
        /** ProviderOAuthStartRequest */
        ProviderOAuthStartRequest: {
            /**
             * Redirect Path
             * @default /settings/providers
             */
            redirect_path: string;
            /** @default read_only */
            requested_scope_tier: components["schemas"]["OAuthScopeTier"];
            /** Requested Services */
            requested_services?: components["schemas"]["ProviderService"][];
            scope?: components["schemas"]["ScopedIdentity"];
        };
        /** ProviderOAuthStartResponse */
        ProviderOAuthStartResponse: {
            /** Authorization Url */
            authorization_url?: string | null;
            /** Configured */
            configured: boolean;
            /** Connection Id */
            connection_id?: string | null;
            /** Detail */
            detail: string;
            /** Expires At */
            expires_at?: string | null;
            provider: components["schemas"]["ProviderKind"];
            /** Requested Scopes */
            requested_scopes?: string[];
        };
        /**
         * ProviderOperationalSyncStatus
         * @enum {string}
         */
        ProviderOperationalSyncStatus: "healthy" | "degraded" | "throttled" | "auth_required" | "stale" | "paused";
        /**
         * ProviderService
         * @enum {string}
         */
        ProviderService: "mail" | "calendar";
        /** ProviderStatusResponse */
        ProviderStatusResponse: {
            /** Accounts */
            accounts?: components["schemas"]["ProviderAccountSummary"][];
            /** Providers */
            providers?: components["schemas"]["ProviderConfigurationStatus"][];
        };
        /** ProviderSyncRequest */
        ProviderSyncRequest: {
            /**
             * Sync Kind
             * @default reconcile
             */
            sync_kind: string;
        };
        /** ProviderSyncResponse */
        ProviderSyncResponse: {
            /** Detail */
            detail: string;
            job?: components["schemas"]["JobRecord"] | null;
            /** Status */
            status: string;
        };
        /**
         * ProviderSyncState
         * @enum {string}
         */
        ProviderSyncState: "idle" | "queued" | "syncing" | "healthy" | "degraded" | "failed";
        /** ProviderWebhookResponse */
        ProviderWebhookResponse: {
            /** Correlation Id */
            correlation_id?: string;
            /**
             * Deduplicated
             * @default false
             */
            deduplicated: boolean;
            /** Detail */
            detail: string;
            job?: components["schemas"]["JobRecord"] | null;
            provider: components["schemas"]["ProviderKind"];
            /** Status */
            status: string;
        };
        /**
         * RiskTier
         * @enum {string}
         */
        RiskTier: "low" | "medium" | "high";
        /** SanitizedContent */
        SanitizedContent: {
            /** Removed Markers */
            removed_markers?: string[];
            /** Risk Flags */
            risk_flags?: string[];
            /** Safe Text */
            safe_text: string;
        };
        /** ScopedIdentity */
        ScopedIdentity: {
            /** Account Id */
            account_id: string;
            /**
             * Purpose
             * @default assistant_operations
             */
            purpose: string;
            /** Space Id */
            space_id: string;
            /** User Id */
            user_id: string;
        };
        /** SecurityInspectionRequest */
        SecurityInspectionRequest: {
            /** Html */
            html: string;
            /**
             * Source Ref
             * @default onebrain://fixture/untrusted
             */
            source_ref: string;
        };
        /** SecurityInspectionResponse */
        SecurityInspectionResponse: {
            firewall: components["schemas"]["FirewallDecision"];
            sanitized: components["schemas"]["SanitizedContent"];
        };
        /** SessionResponse */
        SessionResponse: {
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Identity Source */
            identity_source: string;
            /** Last Used At */
            last_used_at?: string | null;
            scope: components["schemas"]["ScopedIdentity"];
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
        };
        /**
         * TelegramBindingStatus
         * @enum {string}
         */
        TelegramBindingStatus: "pending" | "verified" | "paused" | "revoked" | "expired";
        /** TelegramBindingStatusResponse */
        TelegramBindingStatusResponse: {
            /** Account Id */
            account_id: string;
            /** Audit Correlation Id */
            audit_correlation_id: string;
            /**
             * Binding Id
             * Format: uuid
             */
            binding_id: string;
            /** Correlation Id */
            correlation_id: string;
            /**
             * Paused
             * @default false
             */
            paused: boolean;
            /** Space Id */
            space_id: string;
            status: components["schemas"]["TelegramBindingStatus"];
            /** User Id */
            user_id: string;
            /** Verified At */
            verified_at?: string | null;
        };
        /** TelegramSetupRequest */
        TelegramSetupRequest: {
            /** Bot Token */
            bot_token: string;
            /**
             * Expires In Seconds
             * @default 600
             */
            expires_in_seconds: number;
            scope?: components["schemas"]["ScopedIdentity"];
        };
        /** TelegramSetupResponse */
        TelegramSetupResponse: {
            /** Audit Correlation Id */
            audit_correlation_id: string;
            /** Binding Code */
            binding_code: string;
            /** Binding Command */
            binding_command: string;
            /**
             * Binding Id
             * Format: uuid
             */
            binding_id: string;
            /** Bot Secret Ref */
            bot_secret_ref: string;
            /** Correlation Id */
            correlation_id: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            status: components["schemas"]["TelegramBindingStatus"];
            /** Token Preview */
            token_preview: string;
        };
        /** TelegramTestMessageRequest */
        TelegramTestMessageRequest: {
            /** Idempotency Key */
            idempotency_key?: string | null;
            /**
             * Message
             * @default Telegram is connected to your OneBrain assistant.
             */
            message: string;
        };
        /** TelegramTestMessageResponse */
        TelegramTestMessageResponse: {
            /** Audit Correlation Id */
            audit_correlation_id: string;
            /**
             * Binding Id
             * Format: uuid
             */
            binding_id: string;
            /** Correlation Id */
            correlation_id: string;
            /** Delivery Ref */
            delivery_ref: string;
            /** Detail */
            detail: string;
            /** Event Ref */
            event_ref: string;
            /**
             * Outbox Id
             * Format: uuid
             */
            outbox_id: string;
            /** Status */
            status: string;
        };
        /** TelegramWebhookResponse */
        TelegramWebhookResponse: {
            /** Binding Id */
            binding_id?: string | null;
            /** Command */
            command?: string | null;
            /** Correlation Id */
            correlation_id?: string;
            /** Detail */
            detail: string;
            /** Event Ref */
            event_ref?: string | null;
            /** Status */
            status: string;
        };
        /** TodayBriefItem */
        TodayBriefItem: {
            /** Detail */
            detail: string;
            /** Source Ref */
            source_ref: string;
            /**
             * Status
             * @default ready
             */
            status: string;
            /** Title */
            title: string;
        };
        /** TodayResponse */
        TodayResponse: {
            /** Account Id */
            account_id: string;
            /** Approvals */
            approvals: components["schemas"]["ApprovalCard"][];
            /** Brief */
            brief: components["schemas"]["TodayBriefItem"][];
            /** Calendar */
            calendar?: components["schemas"]["CalendarInsight"][];
            degraded_mode: components["schemas"]["DegradedModeState"];
            /** Follow Ups */
            follow_ups?: components["schemas"]["FollowUpRisk"][];
            /**
             * Inbox Count
             * @default 0
             */
            inbox_count: number;
            /** Local Date */
            local_date: string;
            /** Navigation */
            navigation: components["schemas"]["NavigationItem"][];
            partial_state?: components["schemas"]["WorkdayPartialState"];
            /** Priorities */
            priorities?: components["schemas"]["PriorityItem"][];
            /**
             * Proactive Suggestion
             * @default
             */
            proactive_suggestion: string;
            /** Provider Health */
            provider_health: components["schemas"]["ProviderHealth"][];
            /** Space Id */
            space_id: string;
            /** User Id */
            user_id: string;
        };
        /** TransitionRecord */
        TransitionRecord: {
            /** Actor */
            actor: string;
            channel?: components["schemas"]["ApprovalChannel"] | null;
            /** Correlation Id */
            correlation_id: string;
            from_state: components["schemas"]["ActionState"] | null;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at?: string;
            /** Reason */
            reason: string;
            to_state: components["schemas"]["ActionState"];
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WorkdayBrief */
        WorkdayBrief: {
            /** Brief Id */
            brief_id: string;
            /**
             * Confidence
             * @default 0.75
             */
            confidence: number;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at?: string;
            /** Items */
            items?: components["schemas"]["TodayBriefItem"][];
            /** Local Date */
            local_date: string;
            partial_state?: components["schemas"]["WorkdayPartialState"];
            /** Source Refs */
            source_refs?: string[];
            /** Summary */
            summary: string;
            /** Title */
            title: string;
        };
        /** WorkdayBriefResponse */
        WorkdayBriefResponse: {
            brief: components["schemas"]["WorkdayBrief"];
            partial_state: components["schemas"]["WorkdayPartialState"];
        };
        /** WorkdayCalendarResponse */
        WorkdayCalendarResponse: {
            /** Insights */
            insights?: components["schemas"]["CalendarInsight"][];
            partial_state: components["schemas"]["WorkdayPartialState"];
        };
        /** WorkdayFollowUpsResponse */
        WorkdayFollowUpsResponse: {
            partial_state: components["schemas"]["WorkdayPartialState"];
            /** Risks */
            risks?: components["schemas"]["FollowUpRisk"][];
        };
        /** WorkdayInboxResponse */
        WorkdayInboxResponse: {
            /** Items */
            items?: components["schemas"]["InboxTriageItem"][];
            partial_state: components["schemas"]["WorkdayPartialState"];
        };
        /** WorkdayPartialState */
        WorkdayPartialState: {
            /**
             * Degraded
             * @default false
             */
            degraded: boolean;
            /**
             * Durable
             * @default false
             */
            durable: boolean;
            /**
             * Generated From
             * @default rules
             */
            generated_from: string;
            /** Missing Sources */
            missing_sources?: string[];
            /**
             * Onebrain Available
             * @default true
             */
            onebrain_available: boolean;
            /**
             * Provider Accounts Seen
             * @default 0
             */
            provider_accounts_seen: number;
            /** Reasons */
            reasons?: string[];
            /** Stale Sources */
            stale_sources?: string[];
        };
        /** WorkdayRegenerateRequest */
        WorkdayRegenerateRequest: {
            /** Local Date */
            local_date?: string | null;
            scope?: components["schemas"]["ScopedIdentity"];
            /**
             * Timezone
             * @default UTC
             */
            timezone: string;
        };
        /** WorkdayRegenerateResponse */
        WorkdayRegenerateResponse: {
            /** Detail */
            detail: string;
            job?: components["schemas"]["JobRecord"] | null;
            snapshot: components["schemas"]["WorkdaySnapshot"];
            /** Status */
            status: string;
        };
        /** WorkdaySnapshot */
        WorkdaySnapshot: {
            /** Account Id */
            account_id: string;
            /** Approvals */
            approvals?: components["schemas"]["ApprovalCard"][];
            brief: components["schemas"]["WorkdayBrief"];
            /** Calendar */
            calendar?: components["schemas"]["CalendarInsight"][];
            /** Follow Ups */
            follow_ups?: components["schemas"]["FollowUpRisk"][];
            /**
             * Generated At
             * Format: date-time
             */
            generated_at?: string;
            /** Inbox */
            inbox?: components["schemas"]["InboxTriageItem"][];
            /** Local Date */
            local_date: string;
            /** Navigation */
            navigation?: components["schemas"]["NavigationItem"][];
            partial_state?: components["schemas"]["WorkdayPartialState"];
            /** Priorities */
            priorities?: components["schemas"]["PriorityItem"][];
            /**
             * Proactive Suggestion
             * @default
             */
            proactive_suggestion: string;
            /** Provider Health */
            provider_health?: components["schemas"]["ProviderHealth"][];
            /** Space Id */
            space_id: string;
            /** User Id */
            user_id: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    live_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    ready_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    metrics_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    create_action_v1_actions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActionCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_action_v1_actions__action_id__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                action_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActionApprovalRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    edit_draft_v1_actions__action_id__draft_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                action_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DraftUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    assistant_ask_v1_assistant_ask_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssistantAskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssistantAskResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogoutResponse"];
                };
            };
        };
    };
    session_info_v1_auth_session_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
        };
    };
    create_brain_audit_event_v1_brain_audit_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BrainAuditEventRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrainAuditEventResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_brain_records_v1_brain_records_get: {
        parameters: {
            query: {
                purpose: string;
                record_type?: string;
                intent?: string;
                status?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrainRecordListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_brain_record_v1_brain_records_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BrainRecordCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrainRecordResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_brain_record_v1_brain_records__record_id__get: {
        parameters: {
            query: {
                purpose: string;
            };
            header?: never;
            path: {
                record_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrainRecordResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    propose_draft_v1_drafts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DraftProposalRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    provider_status_v1_providers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderStatusResponse"];
                };
            };
        };
    };
    provider_accounts_v1_providers_accounts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderAccountsResponse"];
                };
            };
        };
    };
    provider_disconnect_v1_providers_accounts__account_id__disconnect_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderDisconnectResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    provider_account_health_v1_providers_accounts__account_id__health_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderAccountHealthResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    provider_sync_v1_providers_accounts__account_id__sync_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProviderSyncRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderSyncResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    provider_oauth_callback_v1_providers_oauth__provider__callback_get: {
        parameters: {
            query?: {
                code?: string;
                state?: string;
                error?: string;
                error_description?: string;
            };
            header?: never;
            path: {
                provider: components["schemas"]["ProviderKind"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderOAuthCallbackResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    provider_oauth_start_v1_providers_oauth__provider__start_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider: components["schemas"]["ProviderKind"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProviderOAuthStartRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderOAuthStartResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    google_provider_webhook_v1_providers_webhooks_google_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderWebhookResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    microsoft_provider_webhook_v1_providers_webhooks_microsoft_post: {
        parameters: {
            query?: {
                validationToken?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                } | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    inspect_untrusted_content_v1_security_inspect_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SecurityInspectionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SecurityInspectionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    telegram_binding_status_v1_telegram_bindings__binding_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                binding_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TelegramBindingStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    telegram_test_message_v1_telegram_bindings__binding_id__test_message_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                binding_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TelegramTestMessageRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TelegramTestMessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    telegram_setup_v1_telegram_setup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TelegramSetupRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TelegramSetupResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    telegram_webhook_v1_telegram_webhook_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Telegram-Bot-Api-Secret-Token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TelegramWebhookResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    today_v1_today_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TodayResponse"];
                };
            };
        };
    };
    workday_brief_v1_workday_brief_get: {
        parameters: {
            query?: {
                local_date?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkdayBriefResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    schedule_morning_brief_v1_workday_brief_schedule_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MorningBriefScheduleRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MorningBriefScheduleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    workday_calendar_v1_workday_calendar_get: {
        parameters: {
            query?: {
                local_date?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkdayCalendarResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    workday_follow_ups_v1_workday_follow_ups_get: {
        parameters: {
            query?: {
                local_date?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkdayFollowUpsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    workday_inbox_v1_workday_inbox_get: {
        parameters: {
            query?: {
                local_date?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkdayInboxResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    workday_regenerate_v1_workday_regenerate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkdayRegenerateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkdayRegenerateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    workday_today_v1_workday_today_get: {
        parameters: {
            query?: {
                local_date?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkdaySnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
