// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

function requireEnv(value: string | undefined, name: string): string {
  if (typeof value === "string" && value.trim().length > 0) {
    return value;
  }
  throw new Error(`Missing required environment variable: ${name}`);
}

const supabaseUrl = requireEnv(SUPABASE_URL, "VITE_SUPABASE_URL");
const supabasePublishableKey = requireEnv(
  SUPABASE_PUBLISHABLE_KEY,
  "VITE_SUPABASE_PUBLISHABLE_KEY",
);

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabasePublishableKey, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
});
